force-app/main/default/objects/HomologationForm__c/HomologationForm__c.object-meta.xml
<CustomObject>
    <label>Homologation Form</label>
    <nameField>
        <label>Homologation Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homologation Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HomologationForm__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Formularios_de_Homologacao</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>HomologationForms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/Required_Fields__c.field-meta.xml
<CustomField>
    <fullName>Required_Fields__c</fullName>
    <label>Required Fields</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IntegrationType__c.field-meta.xml
<CustomField>
    <fullName>IntegrationType__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IntegrationType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NationalPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>NationalPaymentMethod__c</fullName>
    <label>Payment Methods</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NationalPaymentMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payout__c.field-meta.xml
<CustomField>
    <fullName>Payout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acessórios</fullName>
                <label>Acessories</label>
            </value>
            <value>
                <fullName>Conteúdo Adulto</fullName>
                <label>Adult Content</label>
            </value>
            <value>
                <fullName>Bares e Restaurantes</fullName>
                <label>Bars &amp; Restaurants</label>
            </value>
            <value>
                <fullName>Bebidas</fullName>
                <label>Beverage</label>
            </value>
            <value>
                <fullName>Vestuário</fullName>
                <label>Clothing</label>
            </value>
            <value>
                <fullName>Construção civil</fullName>
                <label>Construction &amp; Industry</label>
            </value>
            <value>
                <fullName>Cosméticos</fullName>
                <label>Cosmetics &amp; Beauty</label>
            </value>
            <value>
                <fullName>Criptomoedas</fullName>
                <label>Cryptocurrencies</label>
            </value>
            <value>
                <fullName>D2C</fullName>
            </value>
            <value>
                <fullName>Decoração</fullName>
                <label>Decoration &amp; Home</label>
            </value>
            <value>
                <fullName>Digital</fullName>
                <label>Digital Products &amp; Services</label>
            </value>
            <value>
                <fullName>Dropshipping</fullName>
            </value>
            <value>
                <fullName>Educação</fullName>
                <label>Education</label>
            </value>
            <value>
                <fullName>E-learning</fullName>
                <label>Education &amp; E-learning</label>
            </value>
            <value>
                <fullName>Eletronics</fullName>
            </value>
            <value>
                <fullName>Eventos</fullName>
                <label>Events &amp; Ticketing</label>
            </value>
            <value>
                <fullName>Alimentos</fullName>
                <label>Food</label>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Calçados</fullName>
                <label>Footwear</label>
            </value>
            <value>
                <fullName>Móveis e/ou eletrodomésticos</fullName>
                <label>Furniture</label>
            </value>
            <value>
                <fullName>Jogos de azar e apostas</fullName>
                <label>Gambling &amp; Betting</label>
            </value>
            <value>
                <fullName>Gaming</fullName>
            </value>
            <value>
                <fullName>Grocery</fullName>
            </value>
            <value>
                <fullName>Home Appliances</fullName>
            </value>
            <value>
                <fullName>Hotéis</fullName>
                <label>Hotels</label>
            </value>
            <value>
                <fullName>Joias/Relógios</fullName>
                <label>Jewelry &amp; watches</label>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
            <value>
                <fullName>PSP</fullName>
                <label>Payment Service Providers (PSP)</label>
            </value>
            <value>
                <fullName>Pet</fullName>
                <label>Pet Products &amp; Services</label>
            </value>
            <value>
                <fullName>Produtos físicos</fullName>
                <label>Physical Products</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/NationalPaymentMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pix</fullName>
    </customValue>
    <customValue>
        <fullName>Cartão de Crédito</fullName>
    </customValue>
    <customValue>
        <fullName>Débito Flash</fullName>
    </customValue>
    <customValue>
        <fullName>Boleto Flash</fullName>
    </customValue>
    <masterLabel>Métodos de Pagamentos - Nacional</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HomologationFormCreate.cls
public with sharing class HomologationFormCreate {
    
    @InvocableMethod
    public static void splitString(List<FlowInputs> inputs) {

        System.debug('HomologationFormCreate.splitString called with inputs: ' + inputs);

        if (inputs == null || inputs[0].url == null || inputs[0].opportunityId == null)
            return;

        FlowInputs input = inputs[0];
        System.debug('Input URL: ' + input.url);

        Opportunity opp = [SELECT Id, AccountId,Segmento__c,NationalPaymentMethod__c,IntegrationType__c,Payout__c FROM Opportunity WHERE Id = :input.opportunityId];
        System.debug('Opportunity: ' + opp);
        Boolean isDropshiping = opp.Segmento__c == 'Dropshipping';
        Boolean isPayout = opp.Payout__c;
        Boolean isIntegrationTypeAPIorJS = opp.IntegrationType__c == 'API' || opp.IntegrationType__c == 'JS';
        Boolean isPaymentMethodCreditCard = opp.NationalPaymentMethod__c.contains('Cartão de Crédito');
        Boolean isPaymentMethodBankSlip = opp.NationalPaymentMethod__c.contains('Boleto Flash');

        List<String> requiredFields = HomologationFormHelper.getRequiredFields(opp);

        List<HomologationForm__c> homologationFormsToCreate = new List<HomologationForm__c>();

        if(input.url.contains(';'))
            for(String u : input.url.split(';'))
                homologationFormsToCreate.add(new HomologationForm__c(Opportunity__c = input.opportunityId,Account__c = input.accountId,Name = u,URL__c = u, Required_Fields__c = String.join(requiredFields, ',')));
        else
            homologationFormsToCreate.add(new HomologationForm__c(Opportunity__c = input.opportunityId, Account__c = input.accountId, Name = input.url, URL__c = input.url, Required_Fields__c = String.join(requiredFields, ',')));   
        
        System.debug('homologationFormsToCreate: ' + homologationFormsToCreate);

        if(!homologationFormsToCreate.isEmpty())
            insert homologationFormsToCreate;
        
    }

    public class FlowInputs {
        @InvocableVariable
        public String url;
        @InvocableVariable
        public Id opportunityId;
        @InvocableVariable
        public Id accountId;
    }
    
}