force-app/main/default/objects/HomologationForm__c/HomologationForm__c.object-meta.xml
<CustomObject>
    <label>Homologation Form</label>
    <nameField>
        <label>Homologation Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homologation Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HomologationForm__c/fields/AccountModel__c.field-meta.xml
<CustomField>
    <fullName>AccountModel__c</fullName>
    <label>Account Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Account</fullName>
            </value>
            <value>
                <fullName>Two Accounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/AutomaticCancellation__c.field-meta.xml
<CustomField>
    <fullName>AutomaticCancellation__c</fullName>
    <label>Automatic Cancellation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_and_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/BankSlipEmailService__c.field-meta.xml
<CustomField>
    <fullName>BankSlipEmailService__c</fullName>
    <label>Bank Slip Email Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Bank Slip Confirmation</fullName>
            </value>
            <value>
                <fullName>Bank Slip Reminder</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/BankSlipSmsService__c.field-meta.xml
<CustomField>
    <fullName>BankSlipSmsService__c</fullName>
    <label>Bank Slip SMS Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Bank Slip Confirmation</fullName>
            </value>
            <value>
                <fullName>Bank Slip Reminder</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/BlockRefund__c.field-meta.xml
<CustomField>
    <fullName>BlockRefund__c</fullName>
    <label>Block Refund</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_and_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <formula>true</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/CreditCardRecurrence__c.field-meta.xml
<CustomField>
    <fullName>CreditCardRecurrence__c</fullName>
    <inlineHelpText>Ativação da tokenizaçao do cartão para compras à vista.</inlineHelpText>
    <label>Credit Card Recurrence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_and_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/DefaultSoftDescriptor__c.field-meta.xml
<CustomField>
    <fullName>DefaultSoftDescriptor__c</fullName>
    <description>Please inform the end customer that their credit card statement will show &quot;PB*XXXXXX, PORTO ALEGRE&quot; (XXXXXX will be replaced with your store&apos;s name). The soft descriptor is crucial to avoid chargebacks since most occur because the cardholder needs to identify the store&apos;s name or the city where we are located.</description>
    <inlineHelpText>Please inform the end customer that their credit card statement will show &quot;PB*XXXXXX, PORTO ALEGRE&quot; (XXXXXX will be replaced with your store&apos;s name). The soft descriptor is crucial to avoid chargebacks since most occur because the cardholder needs to identify the store&apos;s name or the city where we are located.</inlineHelpText>
    <label>Default Soft Descriptor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/EmailPackage__c.field-meta.xml
<CustomField>
    <fullName>EmailPackage__c</fullName>
    <label>Email Package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Packages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/InstallmentRecurrence__c.field-meta.xml
<CustomField>
    <fullName>InstallmentRecurrence__c</fullName>
    <inlineHelpText>Ativação da tokenização do cartão para compras parceladas</inlineHelpText>
    <label>Installment Recurrence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_and_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/MccCode__c.field-meta.xml
<CustomField>
    <fullName>MccCode__c</fullName>
    <label>MCC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/NumberOfDays__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDays__c</fullName>
    <defaultValue>2</defaultValue>
    <inlineHelpText>Padrão e mínimo, 2 dias</inlineHelpText>
    <label>Number of days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/OneClickBuyingTokenization__c.field-meta.xml
<CustomField>
    <fullName>OneClickBuyingTokenization__c</fullName>
    <label>One-Click Buying / Tokenization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_and_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>HomologationForms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/PaymentConfirmationEmailService__c.field-meta.xml
<CustomField>
    <fullName>PaymentConfirmationEmailService__c</fullName>
    <label>Payment Confirmation Email Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_and_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/PaymentLinkEmailService__c.field-meta.xml
<CustomField>
    <fullName>PaymentLinkEmailService__c</fullName>
    <label>Payment Link Email Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_and_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/PixEmailService__c.field-meta.xml
<CustomField>
    <fullName>PixEmailService__c</fullName>
    <label>Pix Email Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Pix Confirmation</fullName>
            </value>
            <value>
                <fullName>Pix Reminder</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/PodReminder__c.field-meta.xml
<CustomField>
    <fullName>PodReminder__c</fullName>
    <label>POD Reminder</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/Required_Fields__c.field-meta.xml
<CustomField>
    <fullName>Required_Fields__c</fullName>
    <label>Required Fields</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/ReviewPayeeRegistration__c.field-meta.xml
<CustomField>
    <fullName>ReviewPayeeRegistration__c</fullName>
    <label>Review Payee Registration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_and_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/SmsPackage__c.field-meta.xml
<CustomField>
    <fullName>SmsPackage__c</fullName>
    <label>SMS Package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Packages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/TransactionType__c.field-meta.xml
<CustomField>
    <fullName>TransactionType__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Beneficiaries Only</fullName>
            </value>
            <value>
                <fullName>Establishments Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Packages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
    </customValue>
    <customValue>
        <fullName>10000</fullName>
    </customValue>
    <customValue>
        <fullName>100000</fullName>
    </customValue>
    <masterLabel>Packages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Yes_and_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Yes and No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HomologationFormSelector.cls
public with sharing class HomologationFormSelector {

    @AuraEnabled(cacheable=true)
    public static List<HomologationForm__c> getByOpportunityId(String opportunityId) {
        return [
            SELECT Id,
            Name,
            Completed__c,
            MccCode__c,
            PodReminder__c,
            BlockRefund__c,
            AutomaticCancellation__c,
            NumberOfDays__c,
            CreditCardRecurrence__c,
            DefaultSoftDescriptor__c,
            InstallmentRecurrence__c,
            BankSlipEmailService__c,
            BankSlipSmsService__c,
            PixEmailService__c,
            EmailPackage__c,
            PaymentConfirmationEmailService__c,
            SmsPackage__c,
            PaymentLinkEmailService__c,
            OneClickBuyingTokenization__c,
            AccountModel__c,
            ReviewPayeeRegistration__c,
            TransactionType__c,
            Required_Fields__c
            FROM HomologationForm__c 
            WHERE Opportunity__c = :opportunityId 
            ORDER BY CreatedDate DESC
        ];
    }
}