force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/KYC__c/KYC__c.object-meta.xml
<CustomObject>
    <description>Used to store information from the client about their business.</description>
    <label>KYC</label>
    <nameField>
        <displayFormat>KYC-{00000000}</displayFormat>
        <label>KYC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/KYC__c/fields/Legal_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Legal_Approval_Status__c</fullName>
    <label>Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Added</fullName>
            </value>
            <value>
                <fullName>Approval Requested</fullName>
            </value>
            <value>
                <fullName>Pending Approval Legal</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>KYCs NB</relationshipLabel>
    <relationshipName>KYCs_NB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KYC_XB__c/KYC_XB__c.object-meta.xml
<CustomObject>
    <label>KYC XB</label>
    <nameField>
        <displayFormat>KYC-XB-{0000000}</displayFormat>
        <label>KYC XB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYCs XB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KYC_XB__c/fields/LegalApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalApprovalStatus__c</fullName>
    <label>Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC_XB__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Crossborder_KYCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Antecipation_Frequency_1__c.field-meta.xml
<CustomField>
    <fullName>Antecipation_Frequency_1__c</fullName>
    <label>Credit Card Anticipation Frequency 1°</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Settlement_Frequency_1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Biweekly</fullName>
            </value>
            <value>
                <fullName>Bimonthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Fluxo Médio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Antecipation_Frequency_2__c.field-meta.xml
<CustomField>
    <fullName>Antecipation_Frequency_2__c</fullName>
    <label>Anticipation Frequency 2°</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Settlement_Frequency_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Biweekly</fullName>
            </value>
            <value>
                <fullName>Bimonthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Fluxo Médio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ApplePay__c.field-meta.xml
<CustomField>
    <fullName>ApplePay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apple Pay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Discovery_Meeting__c.field-meta.xml
<CustomField>
    <fullName>Date_Discovery_Meeting__c</fullName>
    <label>Discovery Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityKYCLegalApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>OpportunityKYCLegalApprovalStatus__c</fullName>
    <label>Opportunity KYC Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityRCCLegalApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>OpportunityRCCLegalApprovalStatus__c</fullName>
    <label>Opportunity RCC Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Settlement_Frequency_1__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Frequency_1__c</fullName>
    <label>Credit Card Settlement Frequency 1°</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AntecipationFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Settlement_Frequency_2__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Frequency_2__c</fullName>
    <label>Settlement Frequency 2°</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AntecipationFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/CustomerAcceptance__c.field-meta.xml
<CustomField>
    <fullName>CustomerAcceptance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Acceptance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/OtherQuoteAccepted__c.field-meta.xml
<CustomField>
    <fullName>OtherQuoteAccepted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Other quote was accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RCC__c/RCC__c.object-meta.xml
<CustomObject>
    <label>RCC</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>RCC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RCCS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RCC__c/fields/LegalApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalApprovalStatus__c</fullName>
    <label>Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RCC__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RCCS</relationshipLabel>
    <relationshipName>RCCS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/AntecipationFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Biweekly</fullName>
    </customValue>
    <customValue>
        <fullName>Bimonthly</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Four per month</fullName>
    </customValue>
    <customValue>
        <fullName>Fluxo médio</fullName>
    </customValue>
    <masterLabel>Antecipation Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LegalApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Added</fullName>
        <default>true</default>
        <label>Added</label>
    </customValue>
    <customValue>
        <fullName>Approval Requested</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Approval Legal</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Legal Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : Daniel Belini
 * @group             : 
 * @last modified on  : 06-27-2025
 * @last modified by  : Marcelo Duarte
**/
@isTest
private class OpportunityTriggerHandlerTest {

    @TestSetup
    static void makeData(){
        
        Id standardPricebookId = Test.getStandardPricebookId();

        Lead leadNB = TestDataFactory.createAndInsertLeadNB();
        Lead leadXB = TestDataFactory.createAndInsertLeadXB();
        
        convertLeads(new List<Lead>{ leadNB, leadXB });
        
        Account accNB = [SELECT Id, Name FROM Account WHERE Name = 'company nb'];
		Account accXB = [SELECT Id, Name FROM Account WHERE Name = 'company xb'];
        
        Opportunity oppNB = [SELECT Id, Name, AccountId FROM Opportunity WHERE AccountId = :accNB.Id];
		Opportunity oppXB = [SELECT Id, Name, AccountId FROM Opportunity WHERE AccountId = :accXB.Id];
        
        Contact conNB = [SELECT Id, Name, AccountId FROM Contact WHERE AccountId = :accNB.Id];
		Contact conXB = [SELECT Id, Name, AccountId FROM Contact WHERE AccountId = :accXB.Id];

        Product2 product = new Product2(
            Name = 'Produto Teste',
            IsActive = true
        );
        insert product;

        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = standardPriceBookId,
            Product2Id = product.Id,
            UnitPrice = 100,
            IsActive = true
        );
        insert standardPrice;

        Quote quote = new Quote(
            OpportunityId = oppNB.Id,
            Name = '1234213678',
            Status = 'Draft',
            Pricebook2Id = standardPriceBookId
        );
        insert quote;

        Quote quote2 = new Quote(
            OpportunityId = oppXB.Id,
            Name = '124313',
            Pricebook2Id = standardPriceBookId,
            Status = 'Draft'
        );
        insert quote2;
    }
    
    @isTest
    static void testSubmitKYCForApproval_WithKYC() {
        Opportunity opp = [SELECT Id, RecordTypeId, OpportunityKYCLegalApprovalStatus__c, OpportunityRCCLegalApprovalStatus__c FROM Opportunity WHERE Account.Name = 'company nb' LIMIT 1];
        KYC__c kyc = [SELECT Id, Legal_Approval_Status__c FROM KYC__c WHERE Opportunity__c = :opp.Id LIMIT 1];
        RCC__c rcc = [SELECT Id, LegalApprovalStatus__c FROM RCC__c WHERE Opportunity__c = :opp.Id LIMIT 1];
        
        Test.startTest();
        
        kyc.Legal_Approval_Status__c = 'Approval Requested';
        update kyc;
        
        opp = [SELECT Id, RecordTypeId, OpportunityKYCLegalApprovalStatus__c, OpportunityRCCLegalApprovalStatus__c FROM Opportunity WHERE Account.Name = 'company nb' LIMIT 1];
        System.assertEquals(kyc.Legal_Approval_Status__c, opp.OpportunityKYCLegalApprovalStatus__c);
        System.assertEquals('Approval Requested', opp.OpportunityKYCLegalApprovalStatus__c);

        rcc.LegalApprovalStatus__c = 'Approval Requested';
        update rcc;
        
        Test.stopTest();
        
        opp = [SELECT Id, RecordTypeId, OpportunityKYCLegalApprovalStatus__c, OpportunityRCCLegalApprovalStatus__c FROM Opportunity WHERE Account.Name = 'company nb' LIMIT 1];
        rcc = [SELECT Id, LegalApprovalStatus__c FROM RCC__c WHERE Opportunity__c = :opp.Id LIMIT 1];
        System.assertEquals(rcc.LegalApprovalStatus__c, opp.OpportunityRCCLegalApprovalStatus__c);
        System.assertEquals('Pending Approval Legal', opp.OpportunityRCCLegalApprovalStatus__c);
        System.assertEquals('Pending Approval Legal', opp.OpportunityKYCLegalApprovalStatus__c);
    }
    
    /*
    @isTest
    static void testSubmitKYCForApproval_WithKYC_XB() {
        Opportunity oppXB = [SELECT Id, RecordTypeId, OpportunityKYCLegalApprovalStatus__c, OpportunityRCCLegalApprovalStatus__c FROM Opportunity WHERE Account.Name = 'company xb' LIMIT 1];
        KYC_XB__c kyc_xb = [SELECT Id, LegalApprovalStatus__c FROM KYC_XB__c WHERE Opportunity__c = :oppXB.Id LIMIT 1]; // por algum motivo não acha os registros-teste
        RCC__c rcc = [SELECT Id, LegalApprovalStatus__c FROM RCC__c WHERE Opportunity__c = :oppXB.Id LIMIT 1];
        
        Test.startTest();
        
        kyc_xb.LegalApprovalStatus__c = 'Approval Requested';
        update kyc_xb;
        
        oppXB = [SELECT Id, RecordTypeId, OpportunityKYCLegalApprovalStatus__c, OpportunityRCCLegalApprovalStatus__c FROM Opportunity WHERE Account.Name = 'company xb' LIMIT 1];
        System.assertEquals(kyc_xb.LegalApprovalStatus__c, oppXB.OpportunityKYCLegalApprovalStatus__c);
        System.assertEquals('Approval Requested', oppXB.OpportunityKYCLegalApprovalStatus__c);

        rcc.LegalApprovalStatus__c = 'Approval Requested';
        update rcc;
        
        Test.stopTest();
        
        oppXB = [SELECT Id, RecordTypeId, OpportunityKYCLegalApprovalStatus__c, OpportunityRCCLegalApprovalStatus__c FROM Opportunity WHERE Account.Name = 'company xb' LIMIT 1];
        rcc = [SELECT Id, LegalApprovalStatus__c FROM RCC__c WHERE Opportunity__c = :oppXB.Id LIMIT 1];
        System.assertEquals(rcc.LegalApprovalStatus__c, oppXB.OpportunityRCCLegalApprovalStatus__c);
        System.assertEquals('Pending Approval Legal', oppXB.OpportunityRCCLegalApprovalStatus__c);
        System.assertEquals('Pending Approval Legal', oppXB.OpportunityKYCLegalApprovalStatus__c);
    }
	*/

    @isTest
    static void validateChangeOpportunityFieldsTest() {
        Opportunity opp = [SELECT Id, StageName FROM Opportunity WHERE Account.Name = 'company nb' LIMIT 1];
        opp.Settlement_Frequency_1__c = 'Monthly';
        opp.Settlement_Frequency_2__c = 'Monthly';
        opp.Antecipation_Frequency_1__c = 'Monthly';
        opp.Antecipation_Frequency_2__c = 'Monthly';
        opp.Date_Discovery_Meeting__c = Date.newInstance(2025, 8, 22);
        opp.StageName = 'Closed Won';
        update opp;
    
        Test.startTest();
        try {
            opp.ApplePay__c = true;
            update opp;
        } catch (Exception e) {
            System.assert(e.getMessage().contains('Status da oportunidade não permite alteração de campos'));
        }
        Test.stopTest();
    }
    
    @isTest
    static void testCanCancelQuotesByStatus() {
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Account.Name = 'company xb' LIMIT 1];
        Quote quote = [SELECT Id, Status FROM Quote WHERE OpportunityId = :opp.Id AND Name = '124313' LIMIT 1];
        
        quote.Status = 'Pending Approval Head';
        update quote;
    
        Test.startTest();
        try {
            opp.ApplePay__c = true;
            update opp;
        } catch (Exception e) {
            System.assert(e.getMessage().contains('Alteração de campos não permitida, existe cotação em aprovação'));
        }
        Test.stopTest();
    }
    
    @isTest
    static void testCanCancelQuotesByIsSyncingField() {
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Account.Name = 'company nb' LIMIT 1];
        Quote quote = [SELECT Id FROM Quote WHERE OpportunityId = :opp.Id AND Name = '1234213678' LIMIT 1];
        
        opp.SyncedQuoteId = quote.Id;
        update opp; // Marca quote como sincronizada
    
        Test.startTest();
        try {
            opp.ApplePay__c = true;
            update opp;
        } catch (Exception e) {
            System.assert(e.getMessage().contains('Alteração de campos não permitida, existe cotação sincronizada com a oportunidade.'));
        }
        Test.stopTest();
    }
    
    @isTest
    static void testAfterUpdate() {
        Opportunity opp = [SELECT Id, SyncedQuoteId FROM Opportunity WHERE Account.Name = 'company nb' LIMIT 1];
        Quote quote = [SELECT Id FROM Quote WHERE OpportunityId = :opp.Id AND Name = '1234213678' LIMIT 1];
        
        opp.SyncedQuoteId = quote.Id;
        update opp;
    
        Test.startTest();
        opp.SyncedQuoteId = null;
        update opp;
        Test.stopTest();
    
        Quote updatedQuote = [SELECT CustomerAcceptance__c, OtherQuoteAccepted__c 
                              FROM Quote WHERE Id = :quote.Id];
        System.assertEquals(false, updatedQuote.CustomerAcceptance__c);
        System.assertEquals(false, updatedQuote.OtherQuoteAccepted__c);
    }
    
    @isTest
    static void testAfterInsertCreatesKycRcc() {
        Opportunity oppNB = [SELECT Id, RecordType.DeveloperName FROM Opportunity WHERE Account.Name = 'company nb'];
        List<KYC__c> kycsNB = [SELECT Id FROM KYC__c WHERE Opportunity__c = :oppNB.Id];
        List<RCC__c> rccs = [SELECT Id FROM RCC__c WHERE Opportunity__c = :oppNB.Id];
        
        System.assertEquals(1, kycsNB.size(), 'KYC não criado para Opp NB');
        System.assertEquals(1, rccs.size(), 'RCC não criado para Opp NB');
    }
    
    @isTest
    static void testAfterUpdateSyncedQuoteRemoval() {
        Opportunity opp = [SELECT Id, SyncedQuoteId FROM Opportunity WHERE Account.Name = 'company nb'];
        opp.SyncedQuoteId = null;
        
        Test.startTest();
        update opp;
        Test.stopTest();
        
        List<Quote> updatedQuotes = [SELECT CustomerAcceptance__c FROM Quote WHERE OpportunityId = :opp.Id];
        for (Quote q : updatedQuotes) {
            System.assertEquals(false, q.CustomerAcceptance__c, 'CustomerAcceptance não resetado após remoção de SyncedQuote');
        }
    }
    
    private static void convertLeads(List<Lead> leads) {
        List<Database.LeadConvert> converts = new List<Database.LeadConvert>();
        for(Lead ld : leads) {
            Database.LeadConvert lc = new Database.LeadConvert();
            lc.setLeadId(ld.Id);
            lc.setConvertedStatus('Closed - Converted');
            converts.add(lc);
        }
        Database.convertLead(converts);
    }
}