force-app/main/default/objects/Big_Boost__c/Big_Boost__c.object-meta.xml
<CustomObject>
    <label>Big Boost</label>
    <nameField>
        <label>Big Boost Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Big Boosts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Big_Boost__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <description>In BigBoost query this is the &quot;q&quot; parameter.</description>
    <label>CNPJ</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Big_Boost__c/fields/Dataset__c.field-meta.xml
<CustomField>
    <fullName>Dataset__c</fullName>
    <label>Dataset</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Big_Boost__c/fields/KYC__c.field-meta.xml
<CustomField>
    <fullName>KYC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KYC</label>
    <referenceTo>KYC__c</referenceTo>
    <relationshipLabel>Big Boosts</relationshipLabel>
    <relationshipName>Big_Boosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Big_Boost__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/KYC__c/KYC__c.object-meta.xml
<CustomObject>
    <description>Used to store information from the client about their business.</description>
    <label>KYC</label>
    <nameField>
        <displayFormat>KYC-{00000000}</displayFormat>
        <label>KYC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/InsertBigBoostJob.cls
public class InsertBigBoostJob implements Queueable {
	private Id kycId;
	private String cnpj;
	private String dataset;
	private String result;

	public InsertBigBoostJob(Id kycId, String cnpj, String dataset, String result) {
		this.kycId = kycId;
		this.cnpj = cnpj;
		this.dataset = dataset;
		this.result = result;
	}

	public void execute(QueueableContext context) {
		try {
			Big_Boost__c bigBoost = new Big_Boost__c(
				KYC__c = kycId,
				CNPJ__c = cnpj,
				Dataset__c = dataset,
				Result__c = result
			);
			insert bigBoost;
		} catch (DmlException e) {
			System.debug('DML Exception: ' + e.getMessage());
		}
	}
}