force-app/main/default/objects/Account/fields/Bank_Details_Branch__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Branch__c</fullName>
    <label>Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Details_Checking_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Checking_Account__c</fullName>
    <label>Checking Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Details_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_CNPJ__c</fullName>
    <label>Bank Details CNPJ</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Details_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Company_Name__c</fullName>
    <label>Bank Details Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Details_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Details_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Number__c</fullName>
    <label>Bank Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingComplement__c.field-meta.xml
<CustomField>
    <fullName>BillingComplement__c</fullName>
    <label>Billing Complement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingNumber__c.field-meta.xml
<CustomField>
    <fullName>BillingNumber__c</fullName>
    <label>Billing Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>Fiscal Registration Number (CNPJ)</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerFinalSupportChannelEmail__c.field-meta.xml
<CustomField>
    <fullName>CustomerFinalSupportChannelEmail__c</fullName>
    <label>E-mail of Support to End Customer</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerFinalSupportChannelUrl__c.field-meta.xml
<CustomField>
    <fullName>CustomerFinalSupportChannelUrl__c</fullName>
    <label>URL of Support to End Customer</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Nome_Comercial__c</fullName>
    <label>Nome Comercial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_Empresarial__c.field-meta.xml
<CustomField>
    <fullName>Nome_Empresarial__c</fullName>
    <description>Informar a razão social da empresa, conforme consta no cartão CNPJ.</description>
    <inlineHelpText>Informar a razão social da empresa, conforme consta no cartão CNPJ.</inlineHelpText>
    <label>Legal Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ShippingComplement__c.field-meta.xml
<CustomField>
    <fullName>ShippingComplement__c</fullName>
    <label>Shipping Complement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/HomologationForm__c/HomologationForm__c.object-meta.xml
<CustomObject>
    <label>Homologation Form</label>
    <nameField>
        <label>Homologation Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homologation Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HomologationForm__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Formularios_de_Homologacao</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/AlreadyRequestedReclameAqui__c.field-meta.xml
<CustomField>
    <fullName>AlreadyRequestedReclameAqui__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Já solicitei Reclame aqui</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/Cielo30__c.field-meta.xml
<CustomField>
    <fullName>Cielo30__c</fullName>
    <label>Cielo 3.0</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>E-commerce/checkout URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/MonthlyInterestOnCustomerInstallments__c.field-meta.xml
<CustomField>
    <fullName>MonthlyInterestOnCustomerInstallments__c</fullName>
    <label>Juros mensal de Parcelamento ao cliente</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/NotInterestedInOfferingDiscount__c.field-meta.xml
<CustomField>
    <fullName>NotInterestedInOfferingDiscount__c</fullName>
    <label>I&apos;m not interested in offering discount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <label>I&apos;m not interested in offering discounts</label>
            </value>
            <value>
                <fullName>No</fullName>
                <label>I want to offer discounts</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>HomologationForms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/PagBrasilPix__c.field-meta.xml
<CustomField>
    <fullName>PagBrasilPix__c</fullName>
    <label>PagBrasil Pix</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/PagBrasilSolutionForTransferringFee__c.field-meta.xml
<CustomField>
    <fullName>PagBrasilSolutionForTransferringFee__c</fullName>
    <label>Solução PagBrasil para Transferir taxa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/PbCheckoutDiscount__c.field-meta.xml
<CustomField>
    <fullName>PbCheckoutDiscount__c</fullName>
    <label>PB Checkout Discount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/RequirementInfoValidator__c.field-meta.xml
<CustomField>
    <fullName>RequirementInfoValidator__c</fullName>
    <label>Exigência Validador Infos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/RequirementPriceFormat__c.field-meta.xml
<CustomField>
    <fullName>RequirementPriceFormat__c</fullName>
    <label>Exigência Formato de Preços</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/RequirementResponseTime__c.field-meta.xml
<CustomField>
    <fullName>RequirementResponseTime__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exigência Tempo de Resposta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/RequirementZipCodeValidator__c.field-meta.xml
<CustomField>
    <fullName>RequirementZipCodeValidator__c</fullName>
    <label>Address Check &amp; ZIP Code Validation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/ShopifyDiscount__c.field-meta.xml
<CustomField>
    <fullName>ShopifyDiscount__c</fullName>
    <label>Desconto Shopify</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessModel__c.field-meta.xml
<CustomField>
    <fullName>BusinessModel__c</fullName>
    <label>Desired Business Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessModel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_or_service_website_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_or_service_website_URL__c</fullName>
    <inlineHelpText>Site em que o produto ou serviço será comercializado. Mesmo que o KYC.</inlineHelpText>
    <label>Website URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/NaTional.recordType-meta.xml
<RecordType>
    <fullName>NaTional</fullName>
    <active>true</active>
    <businessProcess>XB%2BNB</businessProcess>
    <label>National</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/IsMain__c.field-meta.xml
<CustomField>
    <fullName>IsMain__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Main</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/BusinessModel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Intermediation</fullName>
    </customValue>
    <customValue>
        <fullName>Gateway</fullName>
    </customValue>
    <customValue>
        <fullName>Pix International</fullName>
    </customValue>
    <customValue>
        <fullName>Pix Roaming</fullName>
    </customValue>
    <masterLabel>Business Model</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityWrapperTest.cls
/**
 * @description       :
 * @author            : Hersilio Belini de Oliveira
 * @group             :
 * @last modified on  : 2025-03-03
 * @last modified by  : Hersilio Belini de Oliveira
**/
@isTest
public class OpportunityWrapperTest {

    @testSetup
    static void setup() {
        // Create test data
        Account testAccount = new Account(
            Name = 'Test Account',
            BillingStreet = '123 Test St',
            BillingCity = 'Test City',
            BillingState = 'TS',
            BillingPostalCode = '12345',
            BillingCountry = 'Test Country',
            BillingLatitude = 37.7749,
            BillingLongitude = -122.4194,
            BillingComplement__c = 'Suite 100',
            BillingNumber__c = '123',
            ShippingStreet = '456 Test St',
            ShippingCity = 'Test City',
            ShippingState = 'TS',
            ShippingPostalCode = '67890',
            ShippingCountry = 'Test Country',
            ShippingLatitude = 37.7749,
            ShippingLongitude = -122.4194,
            ShippingComplement__c = 'Suite 200',
            Nome_Empresarial__c = 'Test Business Name',
            Nome_Comercial__c = 'Test Trade Name',
            CNPJ__c = '60815863080',
            Bank_Details_Number__c = 1,

            Bank_Details_Branch__c = '001',
            Bank_Details_CNPJ__c = '60815863080',
            Bank_Details_Checking_Account__c = '12345678',
            Bank_Details_Name__c = 'Test Bank',
            Bank_Details_Company_Name__c = 'Test Company',
            CustomerFinalSupportChannelUrl__c = 'http://test.com',
            CustomerFinalSupportChannelEmail__c = 'support@test.com'
        );
        insert testAccount;

        Id nationalRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('National').getRecordTypeId();

        Date datClose = Date.today().addDays(30);

        Opportunity testOpportunity = new Opportunity(Name = 'Opp1', CloseDate = datClose, AccountId = testAccount.Id, BusinessModel__c = 'Intermediation', RecordTypeId = nationalRT, StageName = 'Contact', Product_or_service_website_URL__c = 'www.google.com');

        insert testOpportunity;

        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'test.contact@test.com',
            Phone = '123-456-7890',
            AccountId = testAccount.Id
        );
        insert testContact;

        HomologationForm__c testForm = new HomologationForm__c(
            Login__c = 'testlogin',
            Cielo30__c = 'Yes',
            MonthlyInterestOnCustomerInstallments__c = 1.5,
            PbCheckoutDiscount__c = 2.0,
            PagBrasilSolutionForTransferringFee__c = 'Yes',
            ShopifyDiscount__c = 3.0,
            PagBrasilPix__c = 4.0,
            NotInterestedInOfferingDiscount__c = 'Yes',
            RequirementResponseTime__c = 'Yes',
            RequirementPriceFormat__c = 'Yes',
            RequirementZipCodeValidator__c = 'Yes',
            RequirementInfoValidator__c = 'Yes',
            AlreadyRequestedReclameAqui__c = 'Yes',
            Opportunity__c = testOpportunity.Id,
            Account__c = testAccount.Id
        );
        insert testForm;

        Quote testQuote = new Quote(
            OpportunityId = testOpportunity.Id,
            Name = 'Test Quote',
            Pricebook2Id = Test.getStandardPricebookId()
        );
        insert testQuote;

        Product2 prod = new Product2(
            Name = 'Test Product',
            Family = 'Test Product Family'
        );

        insert prod;

        PricebookEntry pb = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = prod.Id,
            UnitPrice = 100.0,
            IsActive = true
        );

        insert pb;

        QuoteLineItem testQuoteLineItem = new QuoteLineItem(
            QuoteId = testQuote.Id,
            PricebookEntryId = Test.getStandardPricebookId(),
            Quantity = 1,
            UnitPrice = 100.0,
            Product2Id = pb.Id,
            IsMain__c = true
        );
        insert testQuoteLineItem;
    }

    @isTest
    static void testOpportunityWrapper() {
        Opportunity testOpportunity = OpportunitySelector.getCompleteOpportunityById([SELECT Id FROM Opportunity LIMIT 1].Id);
        OpportunityWrapper oppWrapper = new OpportunityWrapper(testOpportunity);

        System.assertNotEquals(null, oppWrapper, 'OpportunityWrapper should not be null');
        System.assertNotEquals(null, oppWrapper.account, 'AccountWrapper should not be null');
        System.assertNotEquals(null, oppWrapper.contacts, 'Contacts should not be null');
        System.assertNotEquals(null, oppWrapper.homologationForms, 'HomologationForms should not be null');
    }

    @isTest
    static void testSelecQuotelineItem(){
        Quote quote = [SELECT Id FROM Quote LIMIT 1];

        Test.startTest();
        List<QuoteLineItem> quoteLineItems = QuoteLineItemSelector.getQuoteLineItemByQuoteId(quote.Id);
        Test.stopTest();

        System.assert(quoteLineItems.size() > 0, 'QuoteLineItems should not be empty');
    }
}