force-app/main/default/objects/Account/fields/Bank_Details_Branch__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Branch__c</fullName>
    <label>Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Details_Checking_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Checking_Account__c</fullName>
    <label>Checking Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Details_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_CNPJ__c</fullName>
    <label>Bank Details CNPJ</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Details_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Company_Name__c</fullName>
    <label>Bank Details Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Details_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Details_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Number__c</fullName>
    <label>Bank Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingComplement__c.field-meta.xml
<CustomField>
    <fullName>BillingComplement__c</fullName>
    <label>Billing Complement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingNumber__c.field-meta.xml
<CustomField>
    <fullName>BillingNumber__c</fullName>
    <label>Billing Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>Fiscal Registration Number (CNPJ)</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerFinalSupportChannelEmail__c.field-meta.xml
<CustomField>
    <fullName>CustomerFinalSupportChannelEmail__c</fullName>
    <label>E-mail of Support to End Customer</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerFinalSupportChannelUrl__c.field-meta.xml
<CustomField>
    <fullName>CustomerFinalSupportChannelUrl__c</fullName>
    <label>URL of Support to End Customer</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Nome_Comercial__c</fullName>
    <label>Nome Comercial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_Empresarial__c.field-meta.xml
<CustomField>
    <fullName>Nome_Empresarial__c</fullName>
    <description>Informar a razão social da empresa, conforme consta no cartão CNPJ.</description>
    <inlineHelpText>Informar a razão social da empresa, conforme consta no cartão CNPJ.</inlineHelpText>
    <label>Legal Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ShippingComplement__c.field-meta.xml
<CustomField>
    <fullName>ShippingComplement__c</fullName>
    <label>Shipping Complement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ticket_medio__c.field-meta.xml
<CustomField>
    <fullName>Ticket_medio__c</fullName>
    <description>Informar o preço médio de venda dos produtos.</description>
    <inlineHelpText>Informar o preço médio de venda dos produtos.</inlineHelpText>
    <label>Ticket médio de Vendas</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Transacoes_Mensais__c.field-meta.xml
<CustomField>
    <fullName>Transacoes_Mensais__c</fullName>
    <label>Número de Transações Mensais</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/HomologationForm__c/HomologationForm__c.object-meta.xml
<CustomObject>
    <label>Homologation Form</label>
    <nameField>
        <label>Homologation Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homologation Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HomologationForm__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Formularios_de_Homologacao</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HomologationForm__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>IF(
  ISPICKVAL(Opportunity__r.Product_Type__c, &quot;Physical&quot;),
  &quot;Physical products, please fill in the field below&quot;,
  IF(
    ISPICKVAL(Opportunity__r.Product_Type__c, &quot;Digital&quot;),
    &quot;Not a physical product, please disregard the field below&quot;,
    &quot;&quot;
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Antecipation_Frequency_1__c.field-meta.xml
<CustomField>
    <fullName>Antecipation_Frequency_1__c</fullName>
    <label>Credit Card Anticipation Frequency 1°</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Settlement_Frequency_1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Biweekly</fullName>
            </value>
            <value>
                <fullName>Bimonthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Fluxo Médio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Antecipation_Frequency_2__c.field-meta.xml
<CustomField>
    <fullName>Antecipation_Frequency_2__c</fullName>
    <label>Anticipation Frequency 2°</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Settlement_Frequency_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Biweekly</fullName>
            </value>
            <value>
                <fullName>Bimonthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Fluxo Médio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AverageSalesTicket__c.field-meta.xml
<CustomField>
    <fullName>AverageSalesTicket__c</fullName>
    <inlineHelpText>Average Order Value</inlineHelpText>
    <label>Average Order Value</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessModel__c.field-meta.xml
<CustomField>
    <fullName>BusinessModel__c</fullName>
    <label>Desired Business Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessModel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Integracao__c.field-meta.xml
<CustomField>
    <fullName>Integracao__c</fullName>
    <label>Plataforma Utilizada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InHouse</fullName>
            </value>
            <value>
                <fullName>Shopify</fullName>
            </value>
            <value>
                <fullName>Shopify - Buda</fullName>
            </value>
            <value>
                <fullName>Shopify - CartX</fullName>
            </value>
            <value>
                <fullName>Woocommerce</fullName>
            </value>
            <value>
                <fullName>Magento</fullName>
            </value>
            <value>
                <fullName>Vtex</fullName>
            </value>
            <value>
                <fullName>PrestaShop</fullName>
            </value>
            <value>
                <fullName>OpenCart</fullName>
            </value>
            <value>
                <fullName>ACI</fullName>
            </value>
            <value>
                <fullName>Computop</fullName>
            </value>
            <value>
                <fullName>Salesforce CC</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>NuvemShop</fullName>
            </value>
            <value>
                <fullName>Loja Integrada</fullName>
            </value>
            <value>
                <fullName>Tray</fullName>
            </value>
            <value>
                <fullName>Get Commerce</fullName>
            </value>
            <value>
                <fullName>Outra</fullName>
            </value>
            <value>
                <fullName>InHouse / API</fullName>
            </value>
            <value>
                <fullName>PagBrasil.js</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>Payment Link + API</fullName>
            </value>
            <value>
                <fullName>Paymentl LInk Offline</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>JS</fullName>
                <isActive>false</isActive>
                <label>JS</label>
            </value>
            <value>
                <fullName>Link de Pagamentos</fullName>
                <isActive>false</isActive>
                <label>Link de Pagamentos</label>
            </value>
            <value>
                <fullName>OutraSpecify</fullName>
                <isActive>false</isActive>
                <label>OutraSpecify</label>
            </value>
            <value>
                <fullName>PB Checkout</fullName>
                <isActive>false</isActive>
                <label>PB Checkout</label>
            </value>
            <value>
                <fullName>Shopify with Buda</fullName>
                <isActive>false</isActive>
                <label>Shopify with Buda</label>
            </value>
            <value>
                <fullName>Shopify with Cart Panda</fullName>
                <isActive>false</isActive>
                <label>Shopify with Cart Panda</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NationalPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>NationalPaymentMethod__c</fullName>
    <label>Payment Methods</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NationalPaymentMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/nb_receita_mensal__c.field-meta.xml
<CustomField>
    <fullName>nb_receita_mensal__c</fullName>
    <description>Faixa de faturamento mensal das oportunidades nacionais, em R$.</description>
    <inlineHelpText>Merchant’s potential of total processed volume</inlineHelpText>
    <label>Potential TPV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/previs_fat_rs__c.field-meta.xml
<CustomField>
    <fullName>previs_fat_rs__c</fullName>
    <description>Qual é a previsão de faturamento mensal (R$) do lead no momento de qualificação?</description>
    <inlineHelpText>Total processed volume expected via PagBrasil</inlineHelpText>
    <label>PagBrasil TPV</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_or_service_website_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_or_service_website_URL__c</fullName>
    <inlineHelpText>Site em que o produto ou serviço será comercializado. Mesmo que o KYC.</inlineHelpText>
    <label>Website URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProductClass__c.field-meta.xml
<CustomField>
    <fullName>ProductClass__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductClass</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Settlement_Frequency_1__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Frequency_1__c</fullName>
    <label>Credit Card Settlement Frequency 1°</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AntecipationFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Settlement_Frequency_2__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Frequency_2__c</fullName>
    <label>Settlement Frequency 2°</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AntecipationFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ticket_Medio__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Medio__c</fullName>
    <label>Ticket Médio de Vendas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Transacoes_Mensais__c.field-meta.xml
<CustomField>
    <fullName>Transacoes_Mensais__c</fullName>
    <label>Number of Monthly Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/NaTional.recordType-meta.xml
<RecordType>
    <fullName>NaTional</fullName>
    <active>true</active>
    <businessProcess>XB%2BNB</businessProcess>
    <label>National</label>
</RecordType>

force-app/main/default/globalValueSets/AntecipationFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Biweekly</fullName>
    </customValue>
    <customValue>
        <fullName>Bimonthly</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Four per month</fullName>
    </customValue>
    <customValue>
        <fullName>Fluxo médio</fullName>
    </customValue>
    <masterLabel>Antecipation Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/BusinessModel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Intermediation</fullName>
    </customValue>
    <customValue>
        <fullName>Gateway</fullName>
    </customValue>
    <customValue>
        <fullName>Pix International</fullName>
    </customValue>
    <customValue>
        <fullName>Pix Roaming</fullName>
    </customValue>
    <masterLabel>Business Model</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NationalPaymentMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pix</fullName>
    </customValue>
    <customValue>
        <fullName>Cartão de Crédito</fullName>
    </customValue>
    <customValue>
        <fullName>Débito Flash</fullName>
    </customValue>
    <customValue>
        <fullName>Boleto Flash</fullName>
    </customValue>
    <masterLabel>Métodos de Pagamentos - Nacional</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProductClass.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5122</fullName>
        <label>Drugstores</label>
    </customValue>
    <customValue>
        <fullName>5300</fullName>
        <label>Wholesale Clubs</label>
    </customValue>
    <customValue>
        <fullName>5331</fullName>
        <label>Variety Stores</label>
    </customValue>
    <customValue>
        <fullName>5499</fullName>
        <label>Grocery Stores and Supermarkets</label>
    </customValue>
    <customValue>
        <fullName>5651</fullName>
        <label>Clothing</label>
    </customValue>
    <customValue>
        <fullName>5732</fullName>
        <label>Electronics Stores</label>
    </customValue>
    <customValue>
        <fullName>5734</fullName>
        <label>Computer Software</label>
    </customValue>
    <customValue>
        <fullName>5921</fullName>
        <label>Beer, Wine, Liquor Stores</label>
    </customValue>
    <customValue>
        <fullName>5977</fullName>
        <label>Cosmetic Stores</label>
    </customValue>
    <customValue>
        <fullName>8299</fullName>
        <label>Schools and Educational Services</label>
    </customValue>
    <customValue>
        <fullName>8999</fullName>
        <label>Professional Services</label>
    </customValue>
    <customValue>
        <fullName>7299</fullName>
        <label>Other</label>
    </customValue>
    <masterLabel>Product Class</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Physical</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteLineItemTriggerTest.cls
/**
 * @description       : 
 * @author            : Daniel Belini
 * @group             : 
 * @last modified on  : 08-09-2025
 * @last modified by  : Daniel Belini
**/
@isTest
public class QuoteLineItemTriggerTest {
	@isTest static void testQuoteLineItemTriggerSyncingTrue() {
        // Create test data
        Account testAccount = new Account(
            Name = 'Test Account',
            BillingStreet = '123 Test St',
            BillingCity = 'Test City',
            BillingState = 'TS',
            BillingPostalCode = '12345',
            BillingCountry = 'Test Country',
            BillingLatitude = 37.7749,
            BillingLongitude = -122.4194,
            BillingComplement__c = 'Suite 100',
            BillingNumber__c = '123',
            ShippingStreet = '456 Test St',
            ShippingCity = 'Test City',
            ShippingState = 'TS',
            ShippingPostalCode = '67890',
            ShippingCountry = 'Test Country',
            ShippingLatitude = 37.7749,
            ShippingLongitude = -122.4194,
            ShippingComplement__c = 'Suite 200',
            Nome_Empresarial__c = 'Test Business Name',
            Nome_Comercial__c = 'Test Trade Name',
            CNPJ__c = '60815863080',
            Bank_Details_Number__c = 1,

            Bank_Details_Branch__c = '001',
            Bank_Details_CNPJ__c = '60815863080',
            Bank_Details_Checking_Account__c = '12345678',
            Bank_Details_Name__c = 'Test Bank',
            Bank_Details_Company_Name__c = 'Test Company',
            CustomerFinalSupportChannelUrl__c = 'http://test.com',
            CustomerFinalSupportChannelEmail__c = 'support@test.com'
        );
        insert testAccount;

        Id nationalRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NaTional').getRecordTypeId();

        Date datClose = Date.today().addDays(30);

        Opportunity testOpportunity = new Opportunity(
				Name = 'Opp1',
				CloseDate = datClose,
				AccountId = testAccount.Id,
				RecordTypeId = nationalRT,
				StageName = 'Contact',
				Product_or_service_website_URL__c = 'www.google.com',
				Transacoes_Mensais__c = 1213,
				BusinessModel__c = 'Intermediation',
				NationalPaymentMethod__c = 'Pix',
				AverageSalesTicket__c = 15000.00,
				ProductClass__c = '5331',
				previs_fat_rs__c = 5000.00,
				nb_receita_mensal__c = 50000,
				Integracao__c = 'Salesforce CC',
				Recorrencia__c = 'Yes',
				Ticket_Medio__c = 123,
				Product_Type__c = 'Digital',
				Antecipation_Frequency_1__c = 'Weekly',
				Antecipation_Frequency_2__c = 'Monthly',
				Settlement_Frequency_1__c = 'Weekly',
				Settlement_Frequency_2__c = 'Monthly',
				Segmento__c = 'Gaming',
				IntegrationType__c = 'API',
				PaymentRecurrence__c = 'Sim'
			);

        insert testOpportunity;

        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'test.contact@test.com',
            Phone = '123-456-7890',
            AccountId = testAccount.Id
        );
        insert testContact;

        HomologationForm__c testForm = new HomologationForm__c(
            Login__c = 'testlogin',
            Cielo30__c = 'Yes',
            MonthlyInterestOnCustomerInstallments__c = 1.5,
            PbCheckoutDiscount__c = 2.0,
            PagBrasilSolutionForTransferringFee__c = 'Yes',
            ShopifyDiscount__c = 3.0,
            PagBrasilPix__c = 4.0,
            NotInterestedInOfferingDiscount__c = 'Yes',
            RequirementResponseTime__c = 'Yes',
            RequirementPriceFormat__c = 'Yes',
            RequirementZipCodeValidator__c = 'Integration is not API, a validator already exists',
            RequirementInfoValidator__c = 'Integration is not API, a validator already exists',
            AlreadyRequestedReclameAqui__c = 'Yes',
            Opportunity__c = testOpportunity.Id,
            Account__c = testAccount.Id
        );
        insert testForm;

        Quote testQuote = new Quote(
            OpportunityId = testOpportunity.Id,
            Name = 'Test Quote',
            Pricebook2Id = Test.getStandardPricebookId()
        );
        insert testQuote;

        Product2 prod = new Product2(
            Name = 'Test Product',
            Family = 'Test Product Family',
			IsActive = true
        );

        insert prod;

        PricebookEntry pb = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = prod.Id,
            UnitPrice = 100.0,
            IsActive = true
        );

        insert pb;

        QuoteLineItem testQuoteLineItem = new QuoteLineItem(
            QuoteId = testQuote.Id,
            PricebookEntryId = Test.getStandardPricebookId(),
            Quantity = 1,
            UnitPrice = 100.0,
            Product2Id = pb.Id,
            IsMain__c = true
        );
        insert testQuoteLineItem;
        update testQuoteLineItem;
        
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Id = :testOpportunity.Id LIMIT 1];
		opp.SyncedQuoteId = testQuote.Id;
		update opp;

		// Cria Product2
	}
}