force-app/main/default/objects/Account/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Contacts_Amount__c.field-meta.xml
<CustomField>
    <fullName>Contacts_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Contacts Amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Business_Name__c</fullName>
    <description>Informar a razão social da empresa, conforme consta no cartão CNPJ.</description>
    <inlineHelpText>Informar a razão social da empresa, conforme consta no cartão CNPJ.</inlineHelpText>
    <label>Legal Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/AverageSalesTicket__c.field-meta.xml
<CustomField>
    <fullName>AverageSalesTicket__c</fullName>
    <inlineHelpText>Average Order Value</inlineHelpText>
    <label>Average Order Value</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessModel__c.field-meta.xml
<CustomField>
    <fullName>BusinessModel__c</fullName>
    <label>Desired Business Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessModel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IntegrationType__c.field-meta.xml
<CustomField>
    <fullName>IntegrationType__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IntegrationType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NationalPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>NationalPaymentMethod__c</fullName>
    <label>Payment Methods</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NationalPaymentMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/previs_fat_rs__c.field-meta.xml
<CustomField>
    <fullName>previs_fat_rs__c</fullName>
    <description>Qual é a previsão de faturamento mensal (R$) do lead no momento de qualificação?</description>
    <inlineHelpText>Total processed volume expected via PagBrasil</inlineHelpText>
    <label>PagBrasil TPV</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_or_service_website_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_or_service_website_URL__c</fullName>
    <inlineHelpText>Site em que o produto ou serviço será comercializado. Mesmo que o KYC.</inlineHelpText>
    <label>Website URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProductClass__c.field-meta.xml
<CustomField>
    <fullName>ProductClass__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductClass</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Crossborder.recordType-meta.xml
<RecordType>
    <fullName>Crossborder</fullName>
    <active>true</active>
    <businessProcess>XB%2BNB</businessProcess>
    <label>Cross-border</label>
</RecordType>

force-app/main/default/objects/Pricebook2/fields/BusinessModel__c.field-meta.xml
<CustomField>
    <fullName>BusinessModel__c</fullName>
    <label>Business Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessModel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/IsCrossBoard__c.field-meta.xml
<CustomField>
    <fullName>IsCrossBoard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cross Board</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/CurrencyIsoCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyIsoCode__c</fullName>
    <label>Currency Iso Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRL</fullName>
                <default>true</default>
                <label>BRL</label>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/PercentValue__c.field-meta.xml
<CustomField>
    <fullName>PercentValue__c</fullName>
    <label>PercentValue</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PercentValue__c.field-meta.xml
<CustomField>
    <fullName>PercentValue__c</fullName>
    <description>Valor Porcentual</description>
    <label>Percent Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/UseTaxa__c.field-meta.xml
<CustomField>
    <fullName>UseTaxa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Taxa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Taxes__c/Taxes__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento das taxas relacionadas a oportunidade</description>
    <label>Taxes</label>
    <nameField>
        <label>Taxes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxes__c/fields/BusinessModel__c.field-meta.xml
<CustomField>
    <fullName>BusinessModel__c</fullName>
    <label>Modelo de Negócio</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessModel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxes__c/fields/IntegrationType__c.field-meta.xml
<CustomField>
    <fullName>IntegrationType__c</fullName>
    <label>Tipo Integração</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IntegrationType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxes__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Taxes__c/fields/PercentValue__c.field-meta.xml
<CustomField>
    <fullName>PercentValue__c</fullName>
    <label>Percent Value</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxes__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxes__c/fields/ProductClass__c.field-meta.xml
<CustomField>
    <fullName>ProductClass__c</fullName>
    <label>Product Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductClass</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxes__c/fields/RangeFaixaInicial__c.field-meta.xml
<CustomField>
    <fullName>RangeFaixaInicial__c</fullName>
    <label>Range Faixa Inicial</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxes__c/fields/ReceitaMensalFinal__c.field-meta.xml
<CustomField>
    <fullName>ReceitaMensalFinal__c</fullName>
    <label>Receita Mensal Final</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxes__c/fields/ReceitaMensalInicial__c.field-meta.xml
<CustomField>
    <fullName>ReceitaMensalInicial__c</fullName>
    <label>Receita Mensal Inicial</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxes__c/fields/TicketFinal__c.field-meta.xml
<CustomField>
    <fullName>TicketFinal__c</fullName>
    <label>Ticket Final</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxes__c/fields/TicketInicial__c.field-meta.xml
<CustomField>
    <fullName>TicketInicial__c</fullName>
    <label>Ticket Inicial</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxes__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UnitPrice</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Taxes__c/recordTypes/TaxaBaseAntecipacao.recordType-meta.xml
<RecordType>
    <fullName>TaxaBaseAntecipacao</fullName>
    <active>true</active>
    <label>Taxa Base Antecipação</label>
</RecordType>

force-app/main/default/objects/Taxes__c/recordTypes/TaxaGateway.recordType-meta.xml
<RecordType>
    <fullName>TaxaGateway</fullName>
    <active>true</active>
    <label>Taxa Gateway</label>
</RecordType>

force-app/main/default/objects/Taxes__c/recordTypes/TaxaProcessamento.recordType-meta.xml
<RecordType>
    <fullName>TaxaProcessamento</fullName>
    <active>true</active>
    <label>Taxa Processamento</label>
</RecordType>

force-app/main/default/objects/Taxes__c/recordTypes/TaxaSolucaoPagBrasil.recordType-meta.xml
<RecordType>
    <fullName>TaxaSolucaoPagBrasil</fullName>
    <active>true</active>
    <label>Taxa Solução PagBrasil</label>
</RecordType>

force-app/main/default/globalValueSets/BusinessModel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Intermediation</fullName>
    </customValue>
    <customValue>
        <fullName>Gateway</fullName>
    </customValue>
    <customValue>
        <fullName>Pix International</fullName>
    </customValue>
    <customValue>
        <fullName>Pix Roaming</fullName>
    </customValue>
    <masterLabel>Business Model</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NationalPaymentMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pix</fullName>
    </customValue>
    <customValue>
        <fullName>Cartão de Crédito</fullName>
    </customValue>
    <customValue>
        <fullName>Débito Flash</fullName>
    </customValue>
    <customValue>
        <fullName>Boleto Flash</fullName>
    </customValue>
    <masterLabel>Métodos de Pagamentos - Nacional</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProductClass.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5122</fullName>
        <label>Drugstores</label>
    </customValue>
    <customValue>
        <fullName>5300</fullName>
        <label>Wholesale Clubs</label>
    </customValue>
    <customValue>
        <fullName>5331</fullName>
        <label>Variety Stores</label>
    </customValue>
    <customValue>
        <fullName>5499</fullName>
        <label>Grocery Stores and Supermarkets</label>
    </customValue>
    <customValue>
        <fullName>5651</fullName>
        <label>Clothing</label>
    </customValue>
    <customValue>
        <fullName>5732</fullName>
        <label>Electronics Stores</label>
    </customValue>
    <customValue>
        <fullName>5734</fullName>
        <label>Computer Software</label>
    </customValue>
    <customValue>
        <fullName>5921</fullName>
        <label>Beer, Wine, Liquor Stores</label>
    </customValue>
    <customValue>
        <fullName>5977</fullName>
        <label>Cosmetic Stores</label>
    </customValue>
    <customValue>
        <fullName>8299</fullName>
        <label>Schools and Educational Services</label>
    </customValue>
    <customValue>
        <fullName>8999</fullName>
        <label>Professional Services</label>
    </customValue>
    <customValue>
        <fullName>7299</fullName>
        <label>Other</label>
    </customValue>
    <masterLabel>Product Class</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteTriggerHandlerTest.cls
@isTest
public class QuoteTriggerHandlerTest {

    static Pricebook2 testPriceBook;
    static Pricebook2 testPriceBookCross;
    static Id standardPricebookId;
    
    @testSetup
    static void setupData() {
        standardPricebookId = Test.getStandardPricebookId();
    
        testPriceBook = new Pricebook2(Name = 'Test Pricebook', BusinessModel__c = 'Intermediation', IsActive = true);
        insert testPriceBook;
    
        testPriceBookCross = new Pricebook2(Name = 'Test Pricebook Cross', BusinessModel__c = 'Intermediation', IsActive = true, IsCrossBoard__c = true);
        insert testPriceBookCross;
    
        Product2 product1 = new Product2(Name = 'Product CREDITO', ProductCode = 'CREDITO', IsActive = true);
        Product2 product2 = new Product2(Name = 'Product PACOTE', ProductCode = 'PACOTE', IsActive = true);
        Product2 product3 = new Product2(Name = 'Product BOLETO', ProductCode = 'PIX', IsActive = true);
        Product2 product4 = new Product2(Name = 'Product PACOTE', ProductCode = 'PACOTE', IsActive = true);
        Product2 product5 = new Product2(Name = 'Product PACOTE', ProductCode = 'PACOTE', IsActive = true);
        Product2 product6 = new Product2(Name = 'Product PACOTE', ProductCode = 'PACOTE', IsActive = true, Family = 'Payout');
        Product2 product7 = new Product2(Name = 'Product PACKAGE_', ProductCode = 'PACKAGE_', IsActive = true);
    
        insert new List<Product2>{ product1, product2, product3, product4, product5, product6, product7 };
    
        PricebookEntry standardPriceBookEntry1 = new PricebookEntry(
            Pricebook2Id = standardPricebookId,
            Product2Id = product1.Id,
            UnitPrice = 100.00,
            IsActive = true,
            UseTaxa__c = true
        );
        PricebookEntry standardPriceBookEntry2 = new PricebookEntry(
            Pricebook2Id = standardPricebookId,
            Product2Id = product2.Id,
            UnitPrice = 200.00,
            UseTaxa__c = true,
            IsActive = true
        );
        PricebookEntry standardPriceBookEntry3 = new PricebookEntry(
            Pricebook2Id = standardPricebookId,
            Product2Id = product3.Id,
            UnitPrice = 300.00,
            UseTaxa__c = true,
            IsActive = true
        );
        PricebookEntry standardPriceBookEntry4 = new PricebookEntry(
            Pricebook2Id = standardPricebookId,
            Product2Id = product4.Id,
            UnitPrice = 400.00,
            UseTaxa__c = true,
            IsActive = true
        );
        PricebookEntry standardPriceBookEntry5 = new PricebookEntry(
            Pricebook2Id = standardPricebookId,
            Product2Id = product5.Id,
            UnitPrice = 500.00,
            IsActive = true,
            UseTaxa__c = false
        );
        PricebookEntry standardPriceBookEntry6 = new PricebookEntry(
            Pricebook2Id = standardPricebookId,
            Product2Id = product6.Id,
            UnitPrice = 600.00,
            IsActive = true,
            UseTaxa__c = false
        );
        PricebookEntry standardPriceBookEntry7 = new PricebookEntry(
            Pricebook2Id = standardPricebookId,
            Product2Id = product7.Id,
            UnitPrice = 700.00,
            IsActive = true,
            UseTaxa__c = false
        );
        insert new List<PricebookEntry>{ standardPriceBookEntry1, standardPriceBookEntry2, standardPriceBookEntry3, standardPriceBookEntry4, standardPriceBookEntry5,
        standardPriceBookEntry6, standardPriceBookEntry7 };
    
        PricebookEntry priceBookEntry1 = new PricebookEntry(
            Pricebook2Id = testPriceBook.Id,
            Product2Id = product1.Id,
            UnitPrice = 100.00,
            IsActive = true,
            UseTaxa__c = true
        );
        PricebookEntry priceBookEntry2 = new PricebookEntry(
            Pricebook2Id = testPriceBook.Id,
            Product2Id = product2.Id,
            UnitPrice = 100.00,
            IsActive = true,
            UseTaxa__c = true
        );
        PricebookEntry priceBookEntry3 = new PricebookEntry(
            Pricebook2Id = testPriceBook.Id,
            Product2Id = product3.Id,
            UnitPrice = 200.00,
            IsActive = true,
            UseTaxa__c = true
        );
        PricebookEntry priceBookEntry4 = new PricebookEntry(
            Pricebook2Id = testPriceBook.Id,
            Product2Id = product4.Id,
            UnitPrice = 200.00,
            IsActive = true,
            UseTaxa__c = true
        );
        PricebookEntry priceBookEntry5 = new PricebookEntry(
            Pricebook2Id = testPriceBook.Id,
            Product2Id = product5.Id,
            UnitPrice = 200.00,
            IsActive = true,
            UseTaxa__c = false
        );
        PricebookEntry priceBookEntry6 = new PricebookEntry(
            Pricebook2Id = testPriceBook.Id,
            Product2Id = product6.Id,
            UnitPrice = 200.00,
            IsActive = true,
            UseTaxa__c = false
        );
        PricebookEntry priceBookEntry7 = new PricebookEntry(
            Pricebook2Id = testPriceBookCross.Id,
            CurrencyIsoCode__c = 'EUR',
            Product2Id = product7.Id,
            UnitPrice = 200.00,
            IsActive = true,
            UseTaxa__c = true
        );
    
        insert new List<PricebookEntry>{ priceBookEntry1, priceBookEntry2,priceBookEntry3, priceBookEntry4, priceBookEntry5, priceBookEntry6,
            priceBookEntry7};
    
        Id TaxaGatewayId = Schema.SObjectType.Taxes__c.getRecordTypeInfosByDeveloperName().get('TaxaGateway').getRecordTypeId();
        Id TaxaBaseAntecipacaoId = Schema.SObjectType.Taxes__c.getRecordTypeInfosByDeveloperName().get('TaxaBaseAntecipacao').getRecordTypeId();
        Id TaxaProcessamentoId = Schema.SObjectType.Taxes__c.getRecordTypeInfosByDeveloperName().get('TaxaProcessamento').getRecordTypeId();
        Id TaxaSolucaoPagBrasilId = Schema.SObjectType.Taxes__c.getRecordTypeInfosByDeveloperName().get('TaxaSolucaoPagBrasil').getRecordTypeId();
    
        List<Taxes__c> taxesList = new List<Taxes__c>{
            new Taxes__c(
                Product__c = product2.Id,
                RecordTypeId = TaxaBaseAntecipacaoId,
                PercentValue__c = 5,
                ReceitaMensalInicial__c = 0,
                RangeFaixaInicial__c = 5000,
                ReceitaMensalFinal__c = 15000,
                TicketInicial__c = 0,
                TicketFinal__c = 20000,
                IsActive__c = true
            ),
            new Taxes__c(
                Product__c = product3.Id,
                RecordTypeId = TaxaProcessamentoId,
                PercentValue__c = 10,
                ReceitaMensalInicial__c = 5000,
                RangeFaixaInicial__c = 5000,
                ReceitaMensalFinal__c = 10000,
                TicketInicial__c = 0,
                TicketFinal__c = 20000,
                ProductClass__c = '5331',
                IsActive__c = true
            ),
            new Taxes__c(
                Product__c = product4.Id,
                RecordTypeId = TaxaSolucaoPagBrasilId,
                PercentValue__c = 7,
                IntegrationType__c = 'API',
                ReceitaMensalInicial__c = 0,
                RangeFaixaInicial__c = 5000,
                ReceitaMensalFinal__c = 5000,
                IsActive__c = true
            ),
            new Taxes__c(
                Product__c = product1.Id,
                RecordTypeId = TaxaGatewayId,
                UnitPrice__c = 100,
                PercentValue__c = 10,
                TicketInicial__c = 10000,
                ReceitaMensalInicial__c = 0,
                RangeFaixaInicial__c = 5000,
                TicketFinal__c = 20000,
                ReceitaMensalFinal__c = 10000,
                IsActive__c = true
            ),
            new Taxes__c(
                Product__c = product5.Id,
                RecordTypeId = TaxaProcessamentoId,
                UnitPrice__c = 100,
                TicketInicial__c = 10000,
                ReceitaMensalInicial__c = 0,
                RangeFaixaInicial__c = 5000,
                TicketFinal__c = 20000,
                ReceitaMensalFinal__c = 10000,
                ProductClass__c = '5331',
                IsActive__c = true
            ),
            new Taxes__c(
                Product__c = product6.Id,
                RecordTypeId = TaxaProcessamentoId,
                UnitPrice__c = 200,
                TicketInicial__c = 10000,
                ReceitaMensalInicial__c = 0,
                RangeFaixaInicial__c = 5000,
                TicketFinal__c = 20000,
                ReceitaMensalFinal__c = 10000,
                IsActive__c = true
            ),
            new Taxes__c(
                Product__c = product6.Id,
                RecordTypeId = TaxaProcessamentoId,
                UnitPrice__c = 200,
                TicketInicial__c = 10000,
                ReceitaMensalInicial__c = 0,
                RangeFaixaInicial__c = 5000,
                TicketFinal__c = 20000,
                ReceitaMensalFinal__c = 10000,
                IsActive__c = true
            )
        };
        insert taxesList;
        
        Account acc1 = new Account(
        	Name = 'Account NB',
            Type = 'Nacional (NB)',
            Legal_Business_Name__c = 'NB Account Legal Business Name',
            Billing_Country__c = 'Brazil',
            Contacts_Amount__c = 1
        );
        insert acc1;
        Account acc2 = new Account(
        	Name = 'Account XB',
            Type = 'Cross Border (XB)',
            Legal_Business_Name__c = 'XB Account Legal Business Name',
            Billing_Country__c = 'Brazil',
            Contacts_Amount__c = 1
        );
        insert acc2;
    
        Opportunity oppNB = new Opportunity(
            Name = 'Opportunity NB Test',
            StageName = 'Negotiation',
            CloseDate = Date.today().addDays(30),
            BusinessModel__c = 'Intermediation',
            NationalPaymentMethod__c = 'Cartão de Crédito',
            Product_or_service_website_URL__c = 'www.site.com',
            AverageSalesTicket__c = 15000.00,
            ProductClass__c = '5331',
            previs_fat_rs__c = 5000.00,
            Integracao__c = 'API',
            IntegrationType__c = 'Salesforce',
            Recorrencia__c = 'Yes',
            Transacoes_Mensais__c = 123,
            Ticket_Medio__c = 123,
            PaymentRecurrence__c = 'Não',
            Product_Type__c = 'Physical',
            Segmento__c = 'Gaming',
            nb_receita_mensal__c = 5000.00,
            AccountId = acc1.Id,
            Antecipation_Frequency_1__c = 'Monthly',
            Antecipation_Frequency_2__c = 'Monthly',
            Settlement_Frequency_1__c = 'Monthly',
            Settlement_Frequency_2__c = 'Monthly'
        );
        insert oppNB;
        
        Id recordTypeIdCross = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Crossborder').getRecordTypeId();
        Opportunity oppXB = new Opportunity(
            Name = 'Opportunity XB Test',
            StageName = 'Negotiation',
            CloseDate = Date.today().addDays(30),
            BusinessModel__c = 'Intermediation',
            NationalPaymentMethod__c = 'Cartão de Crédito',
            Product_or_service_website_URL__c = 'www.site.com',
            AverageSalesTicket__c = 15000.00,
            ProductClass__c = '5331',
            previs_fat_rs__c = 5000.00,
            Integracao__c = 'API',
            IntegrationType__c = 'Salesforce',
            Moeda__C = 'USD',
            RecordTypeId = recordTypeIdCross,
            Recorrencia__c = 'Yes',
            Transacoes_Mensais__c = 123,
            Ticket_Medio__c = 123,
            PaymentRecurrence__c = 'Não',
            Product_Type__c = 'Physical',
            Segmento__c = 'Gaming',
            nb_receita_mensal__c = 5000.00,
            AccountId = acc2.Id,
            Antecipation_Frequency_1__c = 'Monthly',
            Antecipation_Frequency_2__c = 'Monthly',
            Settlement_Frequency_1__c = 'Monthly',
            Settlement_Frequency_2__c = 'Monthly'
        );
        insert oppXB;
    }
    
    @isTest
    static void testUpdatePriceBook() {
        Opportunity opp = [SELECT Id, Name FROM Opportunity WHERE Name = 'Opportunity NB Test'];
        
        Quote quote = new Quote(
            OpportunityId = opp.Id,
            Name = 'Test Quote',
            Pricebook2Id = null
        );
        insert quote;
    
        Quote quote2 = new Quote(
            OpportunityId = opp.Id,
            Name = 'Test Quote2',
            Pricebook2Id = null
        );
        insert quote2;
    
        Test.startTest();
        QuoteTriggerHandler handler = new QuoteTriggerHandler(new List<Quote>{quote}, null);
        handler.beforeInsert();
        Test.stopTest();
    
        quote = [SELECT Pricebook2Id FROM Quote WHERE Id = :quote.Id];
        System.assertNotEquals(null, quote.Pricebook2Id, 'O Pricebook2Id deve ter sido definido.');
    }
    
    /*@isTest
    static void testCreateQuoliteItem() {
        Opportunity opp = [SELECT Id, Name FROM Opportunity WHERE Name = 'Opportunity NB Test'];
        
        Quote quote = new Quote(
            OpportunityId = opp.Id,
            Name = 'Test Quote with Items',
            Pricebook2Id = standardPricebookId
        );
        insert quote;
    
        Test.startTest();
        QuoteTriggerHandler handler = new QuoteTriggerHandler(new List<Quote>{quote}, null);
        handler.afterInsert();
        Test.stopTest();
    
        List<QuoteLineItem> quoteLineItems = [SELECT Id, Product2Id, Quantity, UnitPrice, QuoteId FROM QuoteLineItem WHERE QuoteId = :quote.Id];
        System.assert(quoteLineItems.size() > 0, 'QuoteLineItems devem ter sido criados.');
        System.assertEquals(1, quoteLineItems[0].Quantity, 'A quantidade do QuoteLineItem deve ser 1.');
        System.assertEquals(100, quoteLineItems[0].UnitPrice, 'O preço unitário do QuoteLineItem deve ser conforme o PricebookEntry.');
    }*/
    
    @isTest
    static void testWithoutBusiness() {
        Opportunity opp = [SELECT Id, Name FROM Opportunity WHERE Name = 'Opportunity NB Test'];
        
        Quote quote1 = new Quote(OpportunityId = opp.Id, Name = 'Test Quote 1');
    
        Test.startTest();
    
        try {
            insert quote1;
            QuoteTriggerHandler handler = new QuoteTriggerHandler(new List<Quote>{quote1}, null);
            handler.afterInsert();
            System.assert(true, 'A validação deveria ter lançado uma exceção, mas não lançou.');
        } catch (Exception e) {
            System.assert(e.getMessage().contains('Business Model is required'), 'Erro esperado para Business Model não foi capturado.');
        }
    
        Test.stopTest();
    }
    
    @isTest
    static void testWithoutCurrency() {
        Opportunity opp = [SELECT Id, Name FROM Opportunity WHERE Name = 'Opportunity XB Test'];
    
        Quote quote2 = new Quote(OpportunityId = opp.Id, Name = 'Test Quote 2');
    
        Test.startTest();
    
        try {
            insert quote2;
            QuoteTriggerHandler handler = new QuoteTriggerHandler(new List<Quote>{quote2}, null);
            handler.afterInsert();
            System.assert(true, 'A validação deveria ter lançado uma exceção, mas não lançou.');
        } catch (Exception e) {
            System.assert(e.getMessage().contains('Remittance Currency is required'), 'Erro esperado para Remittance Currency não foi capturado.');
        }
    
        Test.stopTest();
    }
    
    @isTest
    static void testCurrencyIsoCode() {
		Opportunity opp = [SELECT Id, Name FROM Opportunity WHERE Name = 'Opportunity XB Test'];
    
        Quote quote2 = new Quote(
            OpportunityId = opp.Id,
            Name = 'Test Quote 2',
            Pricebook2Id = standardPricebookId
        );
    
        Test.startTest();
        insert quote2;
        QuoteTriggerHandler handler = new QuoteTriggerHandler(new List<Quote>{quote2}, null);
        handler.afterInsert();
        Test.stopTest();
    }
}