force-app/main/default/objects/Account/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Contacts_Amount__c.field-meta.xml
<CustomField>
    <fullName>Contacts_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Contacts Amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Business_Name__c</fullName>
    <description>Informar a razão social da empresa, conforme consta no cartão CNPJ.</description>
    <inlineHelpText>Informar a razão social da empresa, conforme consta no cartão CNPJ.</inlineHelpText>
    <label>Legal Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ticket_medio__c.field-meta.xml
<CustomField>
    <fullName>Ticket_medio__c</fullName>
    <description>Informar o preço médio de venda dos produtos.</description>
    <inlineHelpText>Informar o preço médio de venda dos produtos.</inlineHelpText>
    <label>Ticket médio de Vendas</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Transacoes_Mensais__c.field-meta.xml
<CustomField>
    <fullName>Transacoes_Mensais__c</fullName>
    <label>Número de Transações Mensais</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/HomologationForm__c/HomologationForm__c.object-meta.xml
<CustomObject>
    <label>Homologation Form</label>
    <nameField>
        <label>Homologation Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homologation Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HomologationForm__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>IF(
  ISPICKVAL(Opportunity__r.Product_Type__c, &quot;Physical&quot;),
  &quot;Physical products, please fill in the field below&quot;,
  IF(
    ISPICKVAL(Opportunity__r.Product_Type__c, &quot;Digital&quot;),
    &quot;Not a physical product, please disregard the field below&quot;,
    &quot;&quot;
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AverageSalesTicket__c.field-meta.xml
<CustomField>
    <fullName>AverageSalesTicket__c</fullName>
    <inlineHelpText>Average Order Value</inlineHelpText>
    <label>Average Order Value</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessModel__c.field-meta.xml
<CustomField>
    <fullName>BusinessModel__c</fullName>
    <label>Desired Business Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessModel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Integracao__c.field-meta.xml
<CustomField>
    <fullName>Integracao__c</fullName>
    <label>Plataforma Utilizada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InHouse</fullName>
            </value>
            <value>
                <fullName>Shopify</fullName>
            </value>
            <value>
                <fullName>Shopify - Buda</fullName>
            </value>
            <value>
                <fullName>Shopify - CartX</fullName>
            </value>
            <value>
                <fullName>Woocommerce</fullName>
            </value>
            <value>
                <fullName>Magento</fullName>
            </value>
            <value>
                <fullName>Vtex</fullName>
            </value>
            <value>
                <fullName>PrestaShop</fullName>
            </value>
            <value>
                <fullName>OpenCart</fullName>
            </value>
            <value>
                <fullName>ACI</fullName>
            </value>
            <value>
                <fullName>Computop</fullName>
            </value>
            <value>
                <fullName>Salesforce CC</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>NuvemShop</fullName>
            </value>
            <value>
                <fullName>Loja Integrada</fullName>
            </value>
            <value>
                <fullName>Tray</fullName>
            </value>
            <value>
                <fullName>Get Commerce</fullName>
            </value>
            <value>
                <fullName>Outra</fullName>
            </value>
            <value>
                <fullName>InHouse / API</fullName>
            </value>
            <value>
                <fullName>PagBrasil.js</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>Payment Link + API</fullName>
            </value>
            <value>
                <fullName>Paymentl LInk Offline</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>JS</fullName>
                <isActive>false</isActive>
                <label>JS</label>
            </value>
            <value>
                <fullName>Link de Pagamentos</fullName>
                <isActive>false</isActive>
                <label>Link de Pagamentos</label>
            </value>
            <value>
                <fullName>OutraSpecify</fullName>
                <isActive>false</isActive>
                <label>OutraSpecify</label>
            </value>
            <value>
                <fullName>PB Checkout</fullName>
                <isActive>false</isActive>
                <label>PB Checkout</label>
            </value>
            <value>
                <fullName>Shopify with Buda</fullName>
                <isActive>false</isActive>
                <label>Shopify with Buda</label>
            </value>
            <value>
                <fullName>Shopify with Cart Panda</fullName>
                <isActive>false</isActive>
                <label>Shopify with Cart Panda</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IntegrationType__c.field-meta.xml
<CustomField>
    <fullName>IntegrationType__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IntegrationType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NationalPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>NationalPaymentMethod__c</fullName>
    <label>Payment Methods</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NationalPaymentMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentRecurrence__c.field-meta.xml
<CustomField>
    <fullName>PaymentRecurrence__c</fullName>
    <inlineHelpText>Already works with recurring payments?</inlineHelpText>
    <label>Recurring Payments?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>Não</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/previs_fat_rs__c.field-meta.xml
<CustomField>
    <fullName>previs_fat_rs__c</fullName>
    <description>Qual é a previsão de faturamento mensal (R$) do lead no momento de qualificação?</description>
    <inlineHelpText>Total processed volume expected via PagBrasil</inlineHelpText>
    <label>PagBrasil TPV</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_or_service_website_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_or_service_website_URL__c</fullName>
    <inlineHelpText>Site em que o produto ou serviço será comercializado. Mesmo que o KYC.</inlineHelpText>
    <label>Website URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProductClass__c.field-meta.xml
<CustomField>
    <fullName>ProductClass__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductClass</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ticket_Medio__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Medio__c</fullName>
    <label>Ticket Médio de Vendas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Transacoes_Mensais__c.field-meta.xml
<CustomField>
    <fullName>Transacoes_Mensais__c</fullName>
    <label>Number of Monthly Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/BusinessModel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Intermediation</fullName>
    </customValue>
    <customValue>
        <fullName>Gateway</fullName>
    </customValue>
    <customValue>
        <fullName>Pix International</fullName>
    </customValue>
    <customValue>
        <fullName>Pix Roaming</fullName>
    </customValue>
    <masterLabel>Business Model</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NationalPaymentMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pix</fullName>
    </customValue>
    <customValue>
        <fullName>Cartão de Crédito</fullName>
    </customValue>
    <customValue>
        <fullName>Débito Flash</fullName>
    </customValue>
    <customValue>
        <fullName>Boleto Flash</fullName>
    </customValue>
    <masterLabel>Métodos de Pagamentos - Nacional</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProductClass.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5122</fullName>
        <label>Drugstores</label>
    </customValue>
    <customValue>
        <fullName>5300</fullName>
        <label>Wholesale Clubs</label>
    </customValue>
    <customValue>
        <fullName>5331</fullName>
        <label>Variety Stores</label>
    </customValue>
    <customValue>
        <fullName>5499</fullName>
        <label>Grocery Stores and Supermarkets</label>
    </customValue>
    <customValue>
        <fullName>5651</fullName>
        <label>Clothing</label>
    </customValue>
    <customValue>
        <fullName>5732</fullName>
        <label>Electronics Stores</label>
    </customValue>
    <customValue>
        <fullName>5734</fullName>
        <label>Computer Software</label>
    </customValue>
    <customValue>
        <fullName>5921</fullName>
        <label>Beer, Wine, Liquor Stores</label>
    </customValue>
    <customValue>
        <fullName>5977</fullName>
        <label>Cosmetic Stores</label>
    </customValue>
    <customValue>
        <fullName>8299</fullName>
        <label>Schools and Educational Services</label>
    </customValue>
    <customValue>
        <fullName>8999</fullName>
        <label>Professional Services</label>
    </customValue>
    <customValue>
        <fullName>7299</fullName>
        <label>Other</label>
    </customValue>
    <masterLabel>Product Class</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Physical</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HomologationFormApprovalHandlerTest.cls
@isTest
private class HomologationFormApprovalHandlerTest {
    @testSetup
    static void setup() {
        Account acc = new Account(
        	Name = 'QuoteTriggerHandler First Account',
            Type = 'Nacional (NB)',
            Legal_Business_Name__c = 'First Account Legal Business Name',
            Billing_Country__c = 'Brazil',
            Contacts_Amount__c = 1
        );
        insert acc;
        
        Opportunity opp = new Opportunity(
            Name = 'Opportunity NB',
            StageName = 'Negotiation',
            CloseDate = Date.today().addDays(30),
            BusinessModel__c = 'Intermediation',
            NationalPaymentMethod__c = 'Cartão de Crédito',
            Product_or_service_website_URL__c = 'www.site.com',
            AverageSalesTicket__c = 15000.00,
            ProductClass__c = '5331',
            previs_fat_rs__c = 5000.00,
            Integracao__c = 'API',
            IntegrationType__c = 'Salesforce',
            Recorrencia__c = 'Yes',
            Transacoes_Mensais__c = 123,
            Ticket_Medio__c = 123,
            PaymentRecurrence__c = 'Não',
            Product_Type__c = 'Physical',
            Segmento__c = 'Gaming',
            nb_receita_mensal__c = 5000.00,
            AccountId = acc.Id,
            Antecipation_Frequency_1__c = 'Monthly',
            Antecipation_Frequency_2__c = 'Monthly',
            Settlement_Frequency_1__c = 'Monthly',
            Settlement_Frequency_2__c = 'Monthly'
        );
        insert opp;
        HomologationForm__c form = new HomologationForm__c(
            Name = 'Form Teste',
            Opportunity__c = opp.Id,
            Account__c = acc.Id
        );
        insert form;
    }

    static testMethod void testSendApprovalHomologationForm() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Test.startTest();
        try {
            HomologationFormApprovalHandler.sendApprovalHomologationForm(opp.Id);
        } catch (Exception e) {
            // Ignora falha por ausência de processo de aprovação
        }
        Test.stopTest();
        List<HomologationForm__c> updatedForms = [SELECT Legal_Approval_Status__c FROM HomologationForm__c WHERE Opportunity__c = :opp.Id];
        System.assertEquals('Pending Approval Legal', updatedForms[0].Legal_Approval_Status__c);
    }

    static testMethod void testSendApprovalHomologationForm_NoForms() {
        Account acc = new Account(
        	Name = 'QuoteTriggerHandler First Account',
            Type = 'Nacional (NB)',
            Legal_Business_Name__c = 'First Account Legal Business Name',
            Billing_Country__c = 'Brazil',
            Contacts_Amount__c = 1
        );
        insert acc;
        Opportunity opp = new Opportunity(
            Name = 'Opportunity NB 2',
            StageName = 'Negotiation',
            CloseDate = Date.today().addDays(30),
            BusinessModel__c = 'Intermediation',
            NationalPaymentMethod__c = 'Cartão de Crédito',
            Product_or_service_website_URL__c = 'www.site.com',
            AverageSalesTicket__c = 15000.00,
            ProductClass__c = '5331',
            previs_fat_rs__c = 5000.00,
            Integracao__c = 'API',
            IntegrationType__c = 'Salesforce',
            Recorrencia__c = 'Yes',
            Transacoes_Mensais__c = 123,
            Ticket_Medio__c = 123,
            PaymentRecurrence__c = 'Não',
            Product_Type__c = 'Physical',
            Segmento__c = 'Gaming',
            nb_receita_mensal__c = 5000.00,
            AccountId = acc.Id,
            Antecipation_Frequency_1__c = 'Monthly',
            Antecipation_Frequency_2__c = 'Monthly',
            Settlement_Frequency_1__c = 'Monthly',
            Settlement_Frequency_2__c = 'Monthly'
        );
        insert opp;
        Test.startTest();
        HomologationFormApprovalHandler.sendApprovalHomologationForm(opp.Id);
        Test.stopTest();
        System.assertEquals(0, [SELECT count() FROM HomologationForm__c WHERE Opportunity__c = :opp.Id]);
    }
}