force-app/main/default/objects/Account/fields/Filial_no_Brasil__c.field-meta.xml
<CustomField>
    <fullName>Filial_no_Brasil__c</fullName>
    <label>Filial no Brasil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_Empresarial__c.field-meta.xml
<CustomField>
    <fullName>Nome_Empresarial__c</fullName>
    <description>Informar a razão social da empresa, conforme consta no cartão CNPJ.</description>
    <inlineHelpText>Informar a razão social da empresa, conforme consta no cartão CNPJ.</inlineHelpText>
    <label>Legal Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ticket_medio__c.field-meta.xml
<CustomField>
    <fullName>Ticket_medio__c</fullName>
    <description>Informar o preço médio de venda dos produtos.</description>
    <inlineHelpText>Informar o preço médio de venda dos produtos.</inlineHelpText>
    <label>Ticket médio de Vendas</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Transacoes_Mensais__c.field-meta.xml
<CustomField>
    <fullName>Transacoes_Mensais__c</fullName>
    <label>Número de Transações Mensais</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
                <default>true</default>
                <label>Principal</label>
            </value>
            <value>
                <fullName>Técnico</fullName>
            </value>
            <value>
                <fullName>Reembolsos</fullName>
            </value>
            <value>
                <fullName>Notificação</fullName>
            </value>
            <value>
                <fullName>Financeiro</fullName>
            </value>
            <value>
                <fullName>Representante Legal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Antecipation_Frequency_1__c.field-meta.xml
<CustomField>
    <fullName>Antecipation_Frequency_1__c</fullName>
    <label>Credit Card Anticipation Frequency 1°</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Settlement_Frequency_1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Biweekly</fullName>
            </value>
            <value>
                <fullName>Bimonthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Fluxo Médio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Antecipation_Frequency_2__c.field-meta.xml
<CustomField>
    <fullName>Antecipation_Frequency_2__c</fullName>
    <label>Anticipation Frequency 2°</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Settlement_Frequency_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Biweekly</fullName>
            </value>
            <value>
                <fullName>Bimonthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Fluxo Médio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ApplePay__c.field-meta.xml
<CustomField>
    <fullName>ApplePay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apple Pay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AverageSalesTicket__c.field-meta.xml
<CustomField>
    <fullName>AverageSalesTicket__c</fullName>
    <inlineHelpText>Average Order Value</inlineHelpText>
    <label>Average Order Value</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessModel__c.field-meta.xml
<CustomField>
    <fullName>BusinessModel__c</fullName>
    <label>Desired Business Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessModel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Integracao__c.field-meta.xml
<CustomField>
    <fullName>Integracao__c</fullName>
    <label>Plataforma Utilizada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InHouse</fullName>
            </value>
            <value>
                <fullName>Shopify</fullName>
            </value>
            <value>
                <fullName>Shopify - Buda</fullName>
            </value>
            <value>
                <fullName>Shopify - CartX</fullName>
            </value>
            <value>
                <fullName>Woocommerce</fullName>
            </value>
            <value>
                <fullName>Magento</fullName>
            </value>
            <value>
                <fullName>Vtex</fullName>
            </value>
            <value>
                <fullName>PrestaShop</fullName>
            </value>
            <value>
                <fullName>OpenCart</fullName>
            </value>
            <value>
                <fullName>ACI</fullName>
            </value>
            <value>
                <fullName>Computop</fullName>
            </value>
            <value>
                <fullName>Salesforce CC</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>NuvemShop</fullName>
            </value>
            <value>
                <fullName>Loja Integrada</fullName>
            </value>
            <value>
                <fullName>Tray</fullName>
            </value>
            <value>
                <fullName>Get Commerce</fullName>
            </value>
            <value>
                <fullName>Outra</fullName>
            </value>
            <value>
                <fullName>InHouse / API</fullName>
            </value>
            <value>
                <fullName>PagBrasil.js</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>Payment Link + API</fullName>
            </value>
            <value>
                <fullName>Paymentl LInk Offline</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>JS</fullName>
                <isActive>false</isActive>
                <label>JS</label>
            </value>
            <value>
                <fullName>Link de Pagamentos</fullName>
                <isActive>false</isActive>
                <label>Link de Pagamentos</label>
            </value>
            <value>
                <fullName>OutraSpecify</fullName>
                <isActive>false</isActive>
                <label>OutraSpecify</label>
            </value>
            <value>
                <fullName>PB Checkout</fullName>
                <isActive>false</isActive>
                <label>PB Checkout</label>
            </value>
            <value>
                <fullName>Shopify with Buda</fullName>
                <isActive>false</isActive>
                <label>Shopify with Buda</label>
            </value>
            <value>
                <fullName>Shopify with Cart Panda</fullName>
                <isActive>false</isActive>
                <label>Shopify with Cart Panda</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NationalPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>NationalPaymentMethod__c</fullName>
    <label>Payment Methods</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NationalPaymentMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/nb_receita_mensal__c.field-meta.xml
<CustomField>
    <fullName>nb_receita_mensal__c</fullName>
    <description>Faixa de faturamento mensal das oportunidades nacionais, em R$.</description>
    <inlineHelpText>Merchant’s potential of total processed volume</inlineHelpText>
    <label>Potential TPV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/previs_fat_rs__c.field-meta.xml
<CustomField>
    <fullName>previs_fat_rs__c</fullName>
    <description>Qual é a previsão de faturamento mensal (R$) do lead no momento de qualificação?</description>
    <inlineHelpText>Total processed volume expected via PagBrasil</inlineHelpText>
    <label>PagBrasil TPV</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_or_service_website_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_or_service_website_URL__c</fullName>
    <inlineHelpText>Site em que o produto ou serviço será comercializado. Mesmo que o KYC.</inlineHelpText>
    <label>Website URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProductClass__c.field-meta.xml
<CustomField>
    <fullName>ProductClass__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductClass</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Settlement_Frequency_1__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Frequency_1__c</fullName>
    <label>Credit Card Settlement Frequency 1°</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AntecipationFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Settlement_Frequency_2__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Frequency_2__c</fullName>
    <label>Settlement Frequency 2°</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AntecipationFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ticket_Medio__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Medio__c</fullName>
    <label>Ticket Médio de Vendas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Transacoes_Mensais__c.field-meta.xml
<CustomField>
    <fullName>Transacoes_Mensais__c</fullName>
    <label>Number of Monthly Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/AntecipationFrequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Biweekly</fullName>
    </customValue>
    <customValue>
        <fullName>Bimonthly</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Four per month</fullName>
    </customValue>
    <customValue>
        <fullName>Fluxo médio</fullName>
    </customValue>
    <masterLabel>Antecipation Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/BusinessModel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Intermediation</fullName>
    </customValue>
    <customValue>
        <fullName>Gateway</fullName>
    </customValue>
    <customValue>
        <fullName>Pix International</fullName>
    </customValue>
    <customValue>
        <fullName>Pix Roaming</fullName>
    </customValue>
    <masterLabel>Business Model</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NationalPaymentMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pix</fullName>
    </customValue>
    <customValue>
        <fullName>Cartão de Crédito</fullName>
    </customValue>
    <customValue>
        <fullName>Débito Flash</fullName>
    </customValue>
    <customValue>
        <fullName>Boleto Flash</fullName>
    </customValue>
    <masterLabel>Métodos de Pagamentos - Nacional</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProductClass.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5122</fullName>
        <label>Drugstores</label>
    </customValue>
    <customValue>
        <fullName>5300</fullName>
        <label>Wholesale Clubs</label>
    </customValue>
    <customValue>
        <fullName>5331</fullName>
        <label>Variety Stores</label>
    </customValue>
    <customValue>
        <fullName>5499</fullName>
        <label>Grocery Stores and Supermarkets</label>
    </customValue>
    <customValue>
        <fullName>5651</fullName>
        <label>Clothing</label>
    </customValue>
    <customValue>
        <fullName>5732</fullName>
        <label>Electronics Stores</label>
    </customValue>
    <customValue>
        <fullName>5734</fullName>
        <label>Computer Software</label>
    </customValue>
    <customValue>
        <fullName>5921</fullName>
        <label>Beer, Wine, Liquor Stores</label>
    </customValue>
    <customValue>
        <fullName>5977</fullName>
        <label>Cosmetic Stores</label>
    </customValue>
    <customValue>
        <fullName>8299</fullName>
        <label>Schools and Educational Services</label>
    </customValue>
    <customValue>
        <fullName>8999</fullName>
        <label>Professional Services</label>
    </customValue>
    <customValue>
        <fullName>7299</fullName>
        <label>Other</label>
    </customValue>
    <masterLabel>Product Class</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Physical</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrganizationZendeskControllerTest.cls
/**
 * @description       :
 * @author            : Hersilio Belini de Oliveira
 * @group             :
 * @last modified on  : 2025-02-28
 * @last modified by  : Hersilio Belini de Oliveira
**/
@isTest
private class OrganizationZendeskControllerTest {

    @TestSetup
    static void makeData(){

        Account acct = new Account(
            Name = 'Conta teste',
            Filial_no_Brasil__c = 'Sim',
            Nome_Empresarial__c = 'Empresa X',
            BillingCountry = 'Brasil'
        );
        insert acct;

        Contact contact = new Contact(
            LastName = 'Contato teste',
            Type__c = 'Principal',
            AccountId = acct.Id
		);
		insert contact;

		Opportunity opp = new Opportunity(
			Name = 'Opp teste',
			AccountId = acct.Id,
			StageName = 'Contact',
			CloseDate = System.today().addDays(30),
			ApplePay__c = false,
			Product_or_service_website_URL__c = 'https://www.google.com.br/',
			Transacoes_Mensais__c = 1213,
			BusinessModel__c = 'Intermediation',
			NationalPaymentMethod__c = 'Pix',
			AverageSalesTicket__c = 15000.00,
			ProductClass__c = '5331',
			previs_fat_rs__c = 5000.00,
			nb_receita_mensal__c = 50000,
			Integracao__c = 'Salesforce CC',
			Recorrencia__c = 'Yes',
			Ticket_Medio__c = 123,
			Product_Type__c = 'Digital',
			Antecipation_Frequency_1__c = 'Weekly',
			Antecipation_Frequency_2__c = 'Monthly',
			Settlement_Frequency_1__c = 'Weekly',
			Settlement_Frequency_2__c = 'Monthly',
			Segmento__c = 'Gaming',
			IntegrationType__c = 'API',
			PaymentRecurrence__c = 'Sim'
        );
        insert opp;
    }

    @isTest
    static void testCreateOrganization() {

        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Opp Teste' LIMIT 1];
        String organizationId = '34312421321312';
        List<String> domains = new List<String>{'google.com', 'uol.com.br'};
        String timeZone = 'America/Sao_Paulo';

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpServiceMockSuccess());

        OrganizationWrapper  org = OrganizationZendeskController.createOrganization(opp.Id, organizationId, domains, timeZone);

        Test.stopTest();
    }

    @isTest
    static void testCreateOrganizationError() {

        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Opp Teste' LIMIT 1];
        String organizationId = '34312421321312';
        List<String> domains = new List<String>{'google.com', 'uol.com.br'};
        String timeZone = 'America/Sao_Paulo';

        delete [SELECT Id FROM Contact];

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpServiceMockSuccess());
        Boolean error;

        try {
            OrganizationWrapper  org = OrganizationZendeskController.createOrganization(opp.Id, organizationId, domains, timeZone);
        } catch (Exception ex) {
            error = true;
        }

        Test.stopTest();

        System.assertNotEquals(false, error, 'error should be true');
    }

    @isTest
    static void testSearchOrganization() {

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpServiceMockSuccess());
        OrganizationZendeskController.searchOrganization('test');
        Test.stopTest();
    }

    public class HttpServiceMockSuccess implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {

            HTTPResponse res = new HTTPResponse();
            res.setStatusCode(200);
            res.setBody('{ "id" : "34312421321312" }');
            return res;
        }
    }
}