force-app/main/default/objects/Account/fields/Filial_no_Brasil__c.field-meta.xml
<CustomField>
    <fullName>Filial_no_Brasil__c</fullName>
    <label>Filial no Brasil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_Empresarial__c.field-meta.xml
<CustomField>
    <fullName>Nome_Empresarial__c</fullName>
    <description>Informar a razão social da empresa, conforme consta no cartão CNPJ.</description>
    <inlineHelpText>Informar a razão social da empresa, conforme consta no cartão CNPJ.</inlineHelpText>
    <label>Legal Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/BusinessModel__c.field-meta.xml
<CustomField>
    <fullName>BusinessModel__c</fullName>
    <label>Desired Business Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessModel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_or_service_website_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_or_service_website_URL__c</fullName>
    <inlineHelpText>Site em que o produto ou serviço será comercializado. Mesmo que o KYC.</inlineHelpText>
    <label>Website URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/NaTional.recordType-meta.xml
<RecordType>
    <fullName>NaTional</fullName>
    <active>true</active>
    <businessProcess>XB%2BNB</businessProcess>
    <label>National</label>
</RecordType>

force-app/main/default/globalValueSets/BusinessModel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Intermediation</fullName>
    </customValue>
    <customValue>
        <fullName>Gateway</fullName>
    </customValue>
    <customValue>
        <fullName>Pix International</fullName>
    </customValue>
    <customValue>
        <fullName>Pix Roaming</fullName>
    </customValue>
    <masterLabel>Business Model</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunitySelectorTest.cls
/**
 * @description       :
 * @author            : Hersilio Belini de Oliveira
 * @group             :
 * @last modified on  : 2025-03-03
 * @last modified by  : Hersilio Belini de Oliveira
**/
@isTest
public class OpportunitySelectorTest {

    @testSetup
    static void setup() {
        Account acct = new Account(
            Name = 'Conta teste',
            Filial_no_Brasil__c = 'Sim',
            Nome_Empresarial__c = 'Empresa X',
            BillingCountry = 'Brasil'
        );

        insert acct;

        Id nationalRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NaTional').getRecordTypeId();

        Date datClose = Date.today().addDays(30);

        List<Opportunity> opps = new List<Opportunity>{
            new Opportunity(Name = 'Opp1', CloseDate = datClose, AccountId = acct.Id, BusinessModel__c = 'Intermediation', RecordTypeId = nationalRT, StageName = 'Contact', Product_or_service_website_URL__c = 'www.google.com'),
            new Opportunity(Name = 'Opp2', CloseDate = datClose, AccountId = acct.Id, BusinessModel__c = 'Gateway', RecordTypeId = nationalRT, StageName = 'Contact', Product_or_service_website_URL__c = 'www.google.com')
        };

        insert opps;
    }

    @isTest
    static void testGetOpportuniesByIds() {
        // Positive test case
        Set<Id> oppIds = new Set<Id>();
        for (Opportunity opp : [SELECT Id FROM Opportunity]) {
            oppIds.add(opp.Id);
        }
        List<Opportunity> result = OpportunitySelector.getOpportuniesByIds(oppIds);
        System.assertEquals(2, result.size(), 'There should be 2 opportunities');

        // Negative test case
        List<Opportunity> emptyResult = OpportunitySelector.getOpportuniesByIds(new Set<Id>());
        System.assertEquals(0, emptyResult.size(), 'There should be no opportunities');
    }

    @isTest
    static void testGetOpportunityById() {
        // Positive test case
        Opportunity testOpportunity = [SELECT Id FROM Opportunity LIMIT 1];
        Opportunity result = OpportunitySelector.getOpportunityById(testOpportunity.Id);
        System.assertNotEquals(null, result, 'Opportunity should not be null');

        // Negative test case
        Opportunity nullResult = OpportunitySelector.getOpportunityById(null);
        System.assertEquals(null, nullResult, 'Opportunity should be null');
    }

    @isTest
    static void testGetCompleteOpportunityById() {
        // Positive test case
        Opportunity testOpportunity = [SELECT Id FROM Opportunity LIMIT 1];
        Opportunity result = OpportunitySelector.getCompleteOpportunityById(testOpportunity.Id);
        System.assertNotEquals(null, result, 'Opportunity should not be null');

        // Negative test case
        Opportunity nullResult = OpportunitySelector.getCompleteOpportunityById(null);
        System.assertEquals(null, nullResult, 'Opportunity should be null');
    }
}