force-app/main/default/objects/Account/fields/Filial_no_Brasil__c.field-meta.xml
<CustomField>
    <fullName>Filial_no_Brasil__c</fullName>
    <label>Filial no Brasil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_Empresarial__c.field-meta.xml
<CustomField>
    <fullName>Nome_Empresarial__c</fullName>
    <description>Informar a razão social da empresa, conforme consta no cartão CNPJ.</description>
    <inlineHelpText>Informar a razão social da empresa, conforme consta no cartão CNPJ.</inlineHelpText>
    <label>Legal Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Transacoes_Mensais__c.field-meta.xml
<CustomField>
    <fullName>Transacoes_Mensais__c</fullName>
    <label>Número de Transações Mensais</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ApplePay__c.field-meta.xml
<CustomField>
    <fullName>ApplePay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apple Pay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessModel__c.field-meta.xml
<CustomField>
    <fullName>BusinessModel__c</fullName>
    <label>Desired Business Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessModel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DateAccountCreation__c.field-meta.xml
<CustomField>
    <fullName>DateAccountCreation__c</fullName>
    <description>Date for Account Creation</description>
    <inlineHelpText>Date for Account Creation</inlineHelpText>
    <label>Date Account Creation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P0</fullName>
            </value>
            <value>
                <fullName>P1</fullName>
            </value>
            <value>
                <fullName>P2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_or_service_website_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_or_service_website_URL__c</fullName>
    <inlineHelpText>Site em que o produto ou serviço será comercializado. Mesmo que o KYC.</inlineHelpText>
    <label>Website URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Transacoes_Mensais__c.field-meta.xml
<CustomField>
    <fullName>Transacoes_Mensais__c</fullName>
    <label>Number of Monthly Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/BusinessModel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Intermediation</fullName>
    </customValue>
    <customValue>
        <fullName>Gateway</fullName>
    </customValue>
    <customValue>
        <fullName>Pix International</fullName>
    </customValue>
    <customValue>
        <fullName>Pix Roaming</fullName>
    </customValue>
    <masterLabel>Business Model</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ZendeskServiceTest.cls
@isTest
public class ZendeskServiceTest {

    @TestSetup
    static void makeData() {
        Account acct = new Account(
            Name = 'Conta teste',
            Filial_no_Brasil__c = 'Sim',
            Nome_Empresarial__c = 'Empresa X',
            BillingCountry = 'Brasil'
        );
        insert acct;

        Opportunity opp = new Opportunity(
            Name = 'Opp teste',
            AccountId = acct.Id,
            StageName = 'Prospecting',
            CloseDate = System.today().addDays(30),
            ApplePay__c = false,
            Product_or_service_website_URL__c = 'https://www.google.com.br/',
            Transacoes_Mensais__c = 1213,
            BusinessModel__c = 'Intermediation'
        );
        insert opp;
    }

    @isTest
    static void createTicketSuccess() {
        String mockResponse = '{"ticket": {"id": "12345"},"upload": {"token": "abcdef12345"}}';
        HttpResponse mockHttpResponse = new HttpResponse();
        mockHttpResponse.setHeader('Content-Type', 'application/json');
        mockHttpResponse.setBody(mockResponse);
        mockHttpResponse.setStatusCode(201);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(mockHttpResponse));

        Opportunity opp = [
        SELECT Id, AccountId, Priority__c, BusinessModel__c,
        DateAccountCreation__c, Account.Name
        FROM Opportunity 
        WHERE Name = 'Opp teste' 
        LIMIT 1];

        List<String> uploads = new List<String>{'file1.png', 'file2.png'};

        ZendeskTicketWrapper.TicketCheck ticketCheck = new ZendeskTicketWrapper.TicketCheck();
        ticketCheck.pagShieldActivationCheck = true;
        ticketCheck.paymentMethodsInFooter = false;
        ticketCheck.logoInsertionInBoleto = false;
        ticketCheck.reclameAqui = false;
        ticketCheck.pods = false;
        ticketCheck.visualIdentityManualRequest = false;
        ticketCheck.welcomeEmailAndTrainingLinks = true;
        ticketCheck.triggerIndication = 'SIM';

        String organizationId = '12345';

        ZendeskTicketWrapper zendeskWrapper = new ZendeskTicketWrapper(opp, uploads, ticketCheck, organizationId);

        ZendeskService zendeskService = new ZendeskService();

        Test.startTest();
        String ticketId = zendeskService.createTicket(zendeskWrapper);
        Test.stopTest();

        System.assertNotEquals(null, ticketId, 'Ticket ID should not be null.');
        System.assertEquals('12345', ticketId, 'Ticket ID should match the mock response.');
    }

    @isTest
    static void createTicketError() {
        Opportunity opp = [
            SELECT Id, AccountId, Priority__c, BusinessModel__c,
            DateAccountCreation__c, Account.Name 
            FROM Opportunity 
            WHERE Name = 'Opp teste' 
            LIMIT 1
        ];

        List<String> uploads = new List<String>{'file1.png', 'file2.png'};

        ZendeskTicketWrapper.TicketCheck ticketCheck = new ZendeskTicketWrapper.TicketCheck();
        ticketCheck.pagShieldActivationCheck = true;
        ticketCheck.paymentMethodsInFooter = false;
        ticketCheck.logoInsertionInBoleto = false;
        ticketCheck.reclameAqui = false;
        ticketCheck.pods = false;
        ticketCheck.visualIdentityManualRequest = false;
        ticketCheck.welcomeEmailAndTrainingLinks = true;
        ticketCheck.triggerIndication = 'SIM';

        String organizationId = '12345';

        ZendeskTicketWrapper zendeskWrapper = new ZendeskTicketWrapper(opp, uploads, ticketCheck, organizationId);

        ZendeskService zendeskService = new ZendeskService();

        try {
            Test.startTest();
            String ticketId = zendeskService.createTicket(zendeskWrapper);
            Test.stopTest();
        } catch (Exception ex) {
            System.assert(ex.getMessage().contains('Script'), 'Error message should have been thrown.');
        }
    }

    @isTest
    static void createTicketStatusCodeError() {
        String mockResponse = '{"ticket": {"id": "12345"},"upload": {"token": "abcdef12345"}}';
        HttpResponse mockHttpResponse = new HttpResponse();
        mockHttpResponse.setHeader('Content-Type', 'application/json');
        mockHttpResponse.setBody(mockResponse);
        mockHttpResponse.setStatusCode(400);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(mockHttpResponse));

        Opportunity opp = [
        SELECT Id, AccountId, Priority__c, BusinessModel__c,
        DateAccountCreation__c, Account.Name
        FROM Opportunity 
        WHERE Name = 'Opp teste' 
        LIMIT 1];

        List<String> uploads = new List<String>{'file1.png', 'file2.png'};

        ZendeskTicketWrapper.TicketCheck ticketCheck = new ZendeskTicketWrapper.TicketCheck();
        ticketCheck.pagShieldActivationCheck = true;
        ticketCheck.paymentMethodsInFooter = false;
        ticketCheck.logoInsertionInBoleto = false;
        ticketCheck.reclameAqui = false;
        ticketCheck.pods = false;
        ticketCheck.visualIdentityManualRequest = false;
        ticketCheck.welcomeEmailAndTrainingLinks = true;
        ticketCheck.triggerIndication = 'SIM';

        String organizationId = '12345';

        ZendeskTicketWrapper zendeskWrapper = new ZendeskTicketWrapper(opp, uploads, ticketCheck, organizationId);

        ZendeskService zendeskService = new ZendeskService();

        try {
            Test.startTest();
            String ticketId = zendeskService.createTicket(zendeskWrapper);
            Test.stopTest();
            System.assert(false, 'An exception should have been thrown for status 200.');
        } catch (Exception ex) {
            System.assert(ex.getMessage().contains('exception'), 'Error should have been thrown for status 200.');
        }
    }

    @isTest
    static void createAttachSuccess() {
        String mockResponse = '{"ticket": {"id": "12345"},"upload": {"token": "abcdef12345"}}';
        HttpResponse mockHttpResponse = new HttpResponse();
        mockHttpResponse.setHeader('Content-Type', 'application/json');
        mockHttpResponse.setBody(mockResponse);
        mockHttpResponse.setStatusCode(201);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(mockHttpResponse));

        ZendeskService service = new ZendeskService();
        Blob fileBlob = Blob.valueOf('Test content');
        String fileName = 'TestFile.json';

        Test.startTest();
        String token = service.createAttach(fileBlob, fileName, 'json');
        Test.stopTest();

        System.assertNotEquals(null, token, 'Token should not be null.');
        System.assertEquals('abcdef12345', token, 'Token should match the mock response.');
    }

    @isTest
    static void createAttachStatusCodeError() {
        String mockResponse = '{"ticket": {"id": "12345"},"upload": {"token": "abcdef12345"}}';
        HttpResponse mockHttpResponse = new HttpResponse();
        mockHttpResponse.setHeader('Content-Type', 'application/json');
        mockHttpResponse.setBody(mockResponse);
        mockHttpResponse.setStatusCode(400);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(mockHttpResponse));

        ZendeskService service = new ZendeskService();
        Blob fileBlob = Blob.valueOf('Test content');
        String fileName = 'TestFile.json';

        try {
            Test.startTest();
            String token = service.createAttach(fileBlob, fileName, 'json');
            Test.stopTest();
            System.assert(false, 'An exception should have been thrown for status 200.');
        } catch (Exception ex) {
            System.assert(ex.getMessage().contains('exception'), 'Error should have been thrown for status 200.');
        }
    }

    @isTest
    static void createAttachError() {
        ZendeskService service = new ZendeskService();
        Blob fileBlob = Blob.valueOf('Test content');
        String fileName = 'TestFile.json';

        try {
            Test.startTest();
            String token = service.createAttach(fileBlob, fileName, 'json');
            Test.stopTest();
        } catch (Exception ex) {
            System.assert(ex.getMessage().contains('Script'), 'Error message should have been thrown.');
        }
    }

    @isTest
    static void getOrganizationSuccess() {
        String mockResponse = '{"organization": {"id": 12345, "name": "Test Organization"}}';
        HttpResponse mockHttpResponse = new HttpResponse();
        mockHttpResponse.setHeader('Content-Type', 'application/json');
        mockHttpResponse.setBody(mockResponse);
        mockHttpResponse.setStatusCode(200);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(mockHttpResponse));        
        
        String filter = 'Test Organization';

        ZendeskService service = new ZendeskService();

        Test.startTest();
        String response = service.getOrganization(filter);
        Test.stopTest();

        System.assertNotEquals(null, response, 'Response should not be null.');
    }

    @isTest
    static void createOrUpdateOrganizationSuccess() {
        String mockResponse = '{"organization": {"id": 12345, "name": "Test Organization"}}';
        HttpResponse mockHttpResponse = new HttpResponse();
        mockHttpResponse.setHeader('Content-Type', 'application/json');
        mockHttpResponse.setBody(mockResponse);
        mockHttpResponse.setStatusCode(200);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(mockHttpResponse));

        ZendeskService service = new ZendeskService();
        OrganizationWrapper orgWrapper = new OrganizationWrapper();
        orgWrapper.organization.name = 'Test Organization';

        Test.startTest();
        OrganizationWrapper response = service.createOrUpdateOrganization(orgWrapper);
        Test.stopTest();

        System.assertNotEquals(null, response, 'Response should not be null.');
        System.assertEquals('Test Organization', response.organization.name, 'Organization name should match.');
    }

    @isTest
    static void createOrUpdateOrganizationError() {
        String mockResponse = '{"organization": {"id": 12345, "name": "Test Organization"}}';
        HttpResponse mockHttpResponse = new HttpResponse();
        mockHttpResponse.setHeader('Content-Type', 'application/json');
        mockHttpResponse.setBody(mockResponse);
        mockHttpResponse.setStatusCode(400);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(mockHttpResponse));

        ZendeskService service = new ZendeskService();
        OrganizationWrapper orgWrapper = new OrganizationWrapper();
        orgWrapper.organization.name = 'Test Organization';

        try {
            Test.startTest();
            OrganizationWrapper response = service.createOrUpdateOrganization(orgWrapper);
            Test.stopTest();
        } catch (Exception ex) {
            System.assert(ex.getMessage().contains('Script'), 'Error message should have been thrown.');
        }
    }

    public class MockHttpResponseGenerator implements HttpCalloutMock {
        public HttpResponse response;
    
        public MockHttpResponseGenerator(HttpResponse response) {
            this.response = response;
        }
        
        public HttpResponse respond(HttpRequest req) {
            return response;
        }
    }
}