force-app/main/default/objects/Account/fields/Filial_no_Brasil__c.field-meta.xml
<CustomField>
    <fullName>Filial_no_Brasil__c</fullName>
    <label>Filial no Brasil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/KYC__c/KYC__c.object-meta.xml
<CustomObject>
    <description>Used to store information from the client about their business.</description>
    <label>KYC</label>
    <nameField>
        <displayFormat>KYC-{00000000}</displayFormat>
        <label>KYC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/KYC__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KYCs</relationshipLabel>
    <relationshipName>KYCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KYC_XB__c/KYC_XB__c.object-meta.xml
<CustomObject>
    <label>KYC XB</label>
    <nameField>
        <displayFormat>KYC-XB-{0000000}</displayFormat>
        <label>KYC XB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYCs XB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KYC_XB__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KYCs XB</relationshipLabel>
    <relationshipName>KYCs_XB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTriggerTest.cls
@IsTest
private class AccountTriggerTest {

    @IsTest
    static void testAccountTriggerWithFilialBrasilSim() {
        Account acc = new Account(Name = 'Test Account 1', Filial_no_Brasil__c = 'Sim', BillingCountry = 'Brazil');
        insert acc;
        
        List<KYC__c> kycs = [SELECT Id, Client_Account__c FROM KYC__c WHERE Client_Account__c = :acc.Id];
        System.assertEquals(1, kycs.size());
    }

    @IsTest
    static void testAccountTriggerWithFilialBrasilNA() {
        Account acc = new Account(Name = 'Test Account 2', Filial_no_Brasil__c = 'N/A', BillingCountry = 'Brazil');
        insert acc;
        
        List<KYC__c> kycs = [SELECT Id, Client_Account__c FROM KYC__c WHERE Client_Account__c = :acc.Id];
        System.assertEquals(1, kycs.size());
    }

    @IsTest
    static void testAccountTriggerWithOtherFilial() {
        Account acc = new Account(Name = 'Test Account 3', Filial_no_Brasil__c = 'Não', BillingCountry = 'United States');
        insert acc;
        
        List<KYC_XB__c> kycxbs = [SELECT Id, Client_Account__c FROM KYC_XB__c WHERE Client_Account__c = :acc.Id];
        System.assertEquals(1, kycxbs.size());
    }
}