force-app/main/default/objects/Account/fields/Nome_Empresarial__c.field-meta.xml
<CustomField>
    <fullName>Nome_Empresarial__c</fullName>
    <description>Informar a razão social da empresa, conforme consta no cartão CNPJ.</description>
    <inlineHelpText>Informar a razão social da empresa, conforme consta no cartão CNPJ.</inlineHelpText>
    <label>Legal Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Akrotiri</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Arctic Ocean</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Ashmore and Cartier Islands</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IntegrationType__c.field-meta.xml
<CustomField>
    <fullName>IntegrationType__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IntegrationType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Moeda__c.field-meta.xml
<CustomField>
    <fullName>Moeda__c</fullName>
    <label>Remittance Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProductClass__c.field-meta.xml
<CustomField>
    <fullName>ProductClass__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductClass</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TierCS__c.field-meta.xml
<CustomField>
    <fullName>TierCS__c</fullName>
    <label>Tier CS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Top Tier</fullName>
            </value>
            <value>
                <fullName>High Tier</fullName>
            </value>
            <value>
                <fullName>Middle Touch</fullName>
            </value>
            <value>
                <fullName>Low Touch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Website__c.field-meta.xml
<CustomField>
    <fullName>Website__c</fullName>
    <label>Website</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ProductClass.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5122</fullName>
        <label>Drugstores</label>
    </customValue>
    <customValue>
        <fullName>5300</fullName>
        <label>Wholesale Clubs</label>
    </customValue>
    <customValue>
        <fullName>5331</fullName>
        <label>Variety Stores</label>
    </customValue>
    <customValue>
        <fullName>5499</fullName>
        <label>Grocery Stores and Supermarkets</label>
    </customValue>
    <customValue>
        <fullName>5651</fullName>
        <label>Clothing</label>
    </customValue>
    <customValue>
        <fullName>5732</fullName>
        <label>Electronics Stores</label>
    </customValue>
    <customValue>
        <fullName>5734</fullName>
        <label>Computer Software</label>
    </customValue>
    <customValue>
        <fullName>5921</fullName>
        <label>Beer, Wine, Liquor Stores</label>
    </customValue>
    <customValue>
        <fullName>5977</fullName>
        <label>Cosmetic Stores</label>
    </customValue>
    <customValue>
        <fullName>8299</fullName>
        <label>Schools and Educational Services</label>
    </customValue>
    <customValue>
        <fullName>8999</fullName>
        <label>Professional Services</label>
    </customValue>
    <customValue>
        <fullName>7299</fullName>
        <label>Other</label>
    </customValue>
    <masterLabel>Product Class</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Physical</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateOrganizationMethod.cls
/**
 * @description       :
 * @author            : Hersilio Belini de Oliveira
 * @group             :
 * @last modified on  : 2025-01-07
 * @last modified by  : Hersilio Belini de Oliveira
**/
public with sharing class CreateOrganizationMethod {

    @InvocableMethod
    public static void createOrganization(List<FlowInputs> inputs) {
        if (inputs == null || inputs.size() != 1) {
            throw new IllegalArgumentException('This method requires exactly one input object.');
        }

        FlowInputs input = inputs[0];

        if (input.idOpportunity == null) {
            throw new IllegalArgumentException('Opportunity Id is required.');
        }

        Opportunity opportunity = getOpportunity(input.idOpportunity);

    }

    public static Opportunity getOpportunity(Id idOpportunity) {
        List<Opportunity> opps = [
            SELECT
                Id,
                Name,
                Account.Name,
                Account.Nome_Empresarial__c,
                Country__c, Product_Type__c,
                ProductClass__c,
                WebSite__c,
                TierCS__c,
                Moeda__c,
                StageName,
                IntegrationType__c
            FROM Opportunity
            WHERE Id = :idOpportunity
        ];

        if(opps.isEmpty()) {
            throw new AuraHandledException('No Opportunity found with the provided Id.');
        }

        return opps[0];
    }

    public class FlowInputs {
        @InvocableVariable
        public Id idOpportunity;
    }
}