force-app/main/default/objects/Account/fields/Nome_Empresarial__c.field-meta.xml
<CustomField>
    <fullName>Nome_Empresarial__c</fullName>
    <description>Informar a razão social da empresa, conforme consta no cartão CNPJ.</description>
    <inlineHelpText>Informar a razão social da empresa, conforme consta no cartão CNPJ.</inlineHelpText>
    <label>Legal Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATCNPJ__c.field-meta.xml
<CustomField>
    <fullName>VATCNPJ__c</fullName>
    <formula>IF( Fiscal_Number__c != &apos;&apos;,  Fiscal_Number__c,  CNPJ__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT/CNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Akrotiri</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Arctic Ocean</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Ashmore and Cartier Islands</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IntegrationType__c.field-meta.xml
<CustomField>
    <fullName>IntegrationType__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IntegrationType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Moeda__c.field-meta.xml
<CustomField>
    <fullName>Moeda__c</fullName>
    <label>Remittance Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_or_service_website_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_or_service_website_URL__c</fullName>
    <inlineHelpText>Site em que o produto ou serviço será comercializado. Mesmo que o KYC.</inlineHelpText>
    <label>Website URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProductClass__c.field-meta.xml
<CustomField>
    <fullName>ProductClass__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductClass</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TierCS__c.field-meta.xml
<CustomField>
    <fullName>TierCS__c</fullName>
    <label>Tier CS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Top Tier</fullName>
            </value>
            <value>
                <fullName>High Tier</fullName>
            </value>
            <value>
                <fullName>Middle Touch</fullName>
            </value>
            <value>
                <fullName>Low Touch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZendeskValue__c/ZendeskValue__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Zendesk Value</label>
</CustomObject>

force-app/main/default/objects/ZendeskValue__c/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <label>Field Api Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZendeskValue__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZendeskValue__c/fields/SalesforceValue__c.field-meta.xml
<CustomField>
    <fullName>SalesforceValue__c</fullName>
    <label>Salesforce Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZendeskValue__c/fields/ZendeskValue__c.field-meta.xml
<CustomField>
    <fullName>ZendeskValue__c</fullName>
    <label>Zendesk Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ProductClass.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5122</fullName>
        <label>Drugstores</label>
    </customValue>
    <customValue>
        <fullName>5300</fullName>
        <label>Wholesale Clubs</label>
    </customValue>
    <customValue>
        <fullName>5331</fullName>
        <label>Variety Stores</label>
    </customValue>
    <customValue>
        <fullName>5499</fullName>
        <label>Grocery Stores and Supermarkets</label>
    </customValue>
    <customValue>
        <fullName>5651</fullName>
        <label>Clothing</label>
    </customValue>
    <customValue>
        <fullName>5732</fullName>
        <label>Electronics Stores</label>
    </customValue>
    <customValue>
        <fullName>5734</fullName>
        <label>Computer Software</label>
    </customValue>
    <customValue>
        <fullName>5921</fullName>
        <label>Beer, Wine, Liquor Stores</label>
    </customValue>
    <customValue>
        <fullName>5977</fullName>
        <label>Cosmetic Stores</label>
    </customValue>
    <customValue>
        <fullName>8299</fullName>
        <label>Schools and Educational Services</label>
    </customValue>
    <customValue>
        <fullName>8999</fullName>
        <label>Professional Services</label>
    </customValue>
    <customValue>
        <fullName>7299</fullName>
        <label>Other</label>
    </customValue>
    <masterLabel>Product Class</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrganizationWrapper.cls
/**
 * @description       :
 * @author            : Hersilio Belini de Oliveira
 * @group             :
 * @last modified on  : 05-27-2025
 * @last modified by  : Daniel Belini
**/
public class OrganizationWrapper {

    private List<ZendeskValue__c> zendeskValues {
        get {
            if(zendeskValues == null){
                zendeskValues = [SELECT Name, ZendeskValue__c, ObjectName__c, FieldApiName__c, SalesforceValue__c FROM ZendeskValue__c];
            }

            return zendeskValues;
        }

        set;
    }

    @AuraEnabled public Organization organization;

    public OrganizationWrapper() {
        organization = new Organization();
    }

    public OrganizationWrapper(Opportunity opp, Contact contact, List<String> domains, String timezone){
        organization = new Organization();
        organization.name = opp.Account.Name;
        organization.organization_fields = new OrganizationFields();
        organization.organization_fields.comany_name = opp.Account.Nome_Empresarial__c;
        organization.organization_fields.integration_type = opp.IntegrationType__c;
        organization.organization_fields.website = opp.Product_or_service_website_URL__c;
        organization.organization_fields.client_status_comment = opp.StageName;
        organization.organization_fields.product_description = opp.ProductClass__c;
        organization.organization_fields.remittance_currency = opp.Moeda__c;
        organization.organization_fields.end_user_support = contact.Email;
        organization.organization_fields.vat_cnpj = opp.Account.VATCNPJ__c;
        organization.organization_fields.business_size = getZendeskValue('Opportunity', 'TierCS', opp.TierCS__c);
        organization.organization_fields.country = getZendeskValue('Opportunity', 'Country', opp.Country__c);
        organization.organization_fields.contacts_timezone = timezone;
        organization.domain_names = domains;
    }

    public class Organization {
        @AuraEnabled public Long id;
        @AuraEnabled public String name;
        @AuraEnabled public List<String> domain_names;
        @AuraEnabled public OrganizationFields organization_fields;
    }

    public class OrganizationFields {
        @AuraEnabled public String business_size;
        @AuraEnabled public String client_status_comment;
        @AuraEnabled public String comany_name;
        @AuraEnabled public String contacts_timezone;
        @AuraEnabled public String country;
        @AuraEnabled public String end_user_support;
        @AuraEnabled public String integration_type;
        @AuraEnabled public Boolean local_entity;
        @AuraEnabled public String product_description;
        @AuraEnabled public String remittance_currency;
        @AuraEnabled public String website;
        @AuraEnabled public String vat_cnpj;
    }

    // Static method to parse JSON into the wrapper class
    public static OrganizationWrapper fromJSON(String jsonString) {
        return (OrganizationWrapper) JSON.deserialize(jsonString, OrganizationWrapper.class);
    }

    // Static method to serialize the wrapper class into JSON
    public static String toJSON(OrganizationWrapper wrapper) {
        return JSON.serialize(wrapper);
    }

    private String getZendeskValue(String objectName, String fieldName, String value){
        for(ZendeskValue__c zendeskValue : this.zendeskValues){
            if(zendeskValue.ObjectName__c == objectName && zendeskValue.FieldApiName__c == fieldName && zendeskValue.SalesforceValue__c == value){
                return zendeskValue.ZendeskValue__c;
            }
        }

        return '';
    }
}