force-app/main/default/objects/KYC__c/KYC__c.object-meta.xml
<CustomObject>
    <description>Used to store information from the client about their business.</description>
    <label>KYC</label>
    <nameField>
        <displayFormat>KYC-{00000000}</displayFormat>
        <label>KYC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/KYC__c/fields/Legal_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Legal_Approval_Status__c</fullName>
    <label>Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Added</fullName>
            </value>
            <value>
                <fullName>Approval Requested</fullName>
            </value>
            <value>
                <fullName>Pending Approval Legal</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>KYCs NB</relationshipLabel>
    <relationshipName>KYCs_NB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KYC__c/fields/Store_URL__c.field-meta.xml
<CustomField>
    <fullName>Store_URL__c</fullName>
    <label>Store URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/KYC__c/fields/URLs_Quantity__c.field-meta.xml
<CustomField>
    <fullName>URLs_Quantity__c</fullName>
    <label>URLs Quantity</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityKYCLegalApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>OpportunityKYCLegalApprovalStatus__c</fullName>
    <label>Opportunity KYC Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityRCCLegalApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>OpportunityRCCLegalApprovalStatus__c</fullName>
    <label>Opportunity RCC Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LegalApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Added</fullName>
        <default>true</default>
        <label>Added</label>
    </customValue>
    <customValue>
        <fullName>Approval Requested</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Approval Legal</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Legal Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/KYCTriggerHelper.cls
public with sharing class KYCTriggerHelper {
    public static void setURLQuantity(List<KYC__c> newKYCList, Map<Id, KYC__c> oldKYCMap) {
        for (KYC__c record : newKYCList) {
            KYC__c oldRecord = oldKYCMap.get(record.Id);

            if (record.Store_URL__c != oldRecord.Store_URL__c) {
                if (String.isNotBlank(record.Store_URL__c)) {
                    List<String> rawUrls = record.Store_URL__c.split(';');
                    List<String> cleanedUrls = new List<String>();

                    for (String url : rawUrls) {
                        String trimmed = url.trim();
                        if (!String.isEmpty(trimmed)) {
                            cleanedUrls.add(trimmed);
                        }
                    }

                    record.URLs_Quantity__c = cleanedUrls.size();
                } else {
                    record.URLs_Quantity__c = 0;
                }
            }
        }
    }

    public static void updateOpportunityLegalApprovalStatus(List<KYC__c> newKYCList, Map<Id, KYC__c> oldKYCMap) {
        Set<Id> oppIds = new Set<Id>();
        for (KYC__c kyc : newKYCList) {
            if (kyc.Opportunity__c != null) {
                oppIds.add(kyc.Opportunity__c);
            }
        }

        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>([SELECT Id, RecordTypeId, OpportunityRCCLegalApprovalStatus__c, OpportunityKYCLegalApprovalStatus__c FROM Opportunity WHERE Id IN :oppIds]);

        for (KYC__c kyc : newKYCList) {
            if (kyc.Opportunity__c != null && oppMap.containsKey(kyc.Opportunity__c)) {
                Opportunity opp = oppMap.get(kyc.Opportunity__c);
                if (kyc.Legal_Approval_Status__c != oldKYCMap.get(kyc.Id).Legal_Approval_Status__c) {
                    opp.OpportunityKYCLegalApprovalStatus__c = kyc.Legal_Approval_Status__c;
                }
            }
        }

        if (!oppMap.isEmpty()) {
            update oppMap.values();
        }

        // OpportunityTriggerHelper.submitKYCAndRCCForApprovalHandler(oppMap.values());
    }
}