force-app/main/default/objects/KYC__c/KYC__c.object-meta.xml
<CustomObject>
    <description>Used to store information from the client about their business.</description>
    <label>KYC</label>
    <nameField>
        <displayFormat>KYC-{00000000}</displayFormat>
        <label>KYC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/KYC__c/fields/Legal_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Legal_Approval_Status__c</fullName>
    <label>Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Added</fullName>
            </value>
            <value>
                <fullName>Approval Requested</fullName>
            </value>
            <value>
                <fullName>Pending Approval Legal</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>KYCs NB</relationshipLabel>
    <relationshipName>KYCs_NB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KYC_XB__c/KYC_XB__c.object-meta.xml
<CustomObject>
    <label>KYC XB</label>
    <nameField>
        <displayFormat>KYC-XB-{0000000}</displayFormat>
        <label>KYC XB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYCs XB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KYC_XB__c/fields/LegalApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalApprovalStatus__c</fullName>
    <label>Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC_XB__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Crossborder_KYCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RCC__c/RCC__c.object-meta.xml
<CustomObject>
    <label>RCC</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>RCC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RCCS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RCC__c/fields/LegalApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalApprovalStatus__c</fullName>
    <label>Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RCC__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RCCS</relationshipLabel>
    <relationshipName>RCCS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/LegalApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Added</fullName>
        <default>true</default>
        <label>Added</label>
    </customValue>
    <customValue>
        <fullName>Approval Requested</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Approval Legal</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Legal Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ApprovalKYCHandler.cls
public with sharing class ApprovalKYCHandler {
    @AuraEnabled
    public static String updateApprovalStatus(Id recordId) {
        SObject record = Database.query(
            '' + (recordId.getSObjectType() == KYC_XB__c.SObjectType ? 'SELECT LegalApprovalStatus__c, Opportunity__c FROM KYC_XB__c' : 'SELECT Legal_Approval_Status__c, Opportunity__c FROM KYC__c') + ' WHERE Id = :recordId LIMIT 1'
        );

        Id opportunityId;

        if (record != null) {
            if (record instanceof KYC_XB__c) {
                KYC_XB__c xbRecord = (KYC_XB__c) record;

                opportunityId = xbRecord.Opportunity__c;

                xbRecord.LegalApprovalStatus__c = 'Approval Requested';
                update xbRecord;
            } else if (record instanceof KYC__c) {
                KYC__c nbRecord = (KYC__c) record;

                opportunityId = nbRecord.Opportunity__c;

                nbRecord.Legal_Approval_Status__c = 'Approval Requested';
                update nbRecord;
            }
        } else {
            throw new AuraHandledException('Record not found');
        }

        System.debug('opportunityId: ' + opportunityId);

        String opportunityRccLegalStatus = [SELECT LegalApprovalStatus__c FROM RCC__c WHERE Opportunity__c = :opportunityId LIMIT 1].LegalApprovalStatus__c;

        if (opportunityRccLegalStatus != null) {
            return opportunityRccLegalStatus;
        } else {
            return '';
        }
    }
}