force-app/main/default/objects/Lead/fields/Ag_ncia__c.field-meta.xml
<CustomField>
    <fullName>Ag_ncia__c</fullName>
    <description>Cite a agência responsável pelo desenvolvimento do site.</description>
    <label>Agency</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/AtendimentoWhatsApp__c.field-meta.xml
<CustomField>
    <fullName>AtendimentoWhatsApp__c</fullName>
    <label>Support via WhatsApp</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/AverageSalesTicket__c.field-meta.xml
<CustomField>
    <fullName>AverageSalesTicket__c</fullName>
    <inlineHelpText>Antigo &quot;Ticket Médio&quot;</inlineHelpText>
    <label>Average Order Value</label>
    <precision>17</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Boleto_Share__c.field-meta.xml
<CustomField>
    <fullName>Boleto_Share__c</fullName>
    <label>Boleto (% monthly share)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Model_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Model_Type__c</fullName>
    <label>Business Model Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Business_Model_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Cartao_Credito_Mensal__c.field-meta.xml
<CustomField>
    <fullName>Cartao_Credito_Mensal__c</fullName>
    <label>Credit Card (% monthly share)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Cartao_Debito_Mensal__c.field-meta.xml
<CustomField>
    <fullName>Cartao_Debito_Mensal__c</fullName>
    <label>Debit Card (% monthly share)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/cf_email_indicador__c.field-meta.xml
<CustomField>
    <fullName>cf_email_indicador__c</fullName>
    <label>Indicator Email</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Billing City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact_City__c.field-meta.xml
<CustomField>
    <fullName>Contact_City__c</fullName>
    <label>Contact City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Data_de_indicacao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_indicacao__c</fullName>
    <description>Data da indicação do lead</description>
    <inlineHelpText>Data da indicação do lead</inlineHelpText>
    <label>Data de indicação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DataAgendamento__c.field-meta.xml
<CustomField>
    <fullName>DataAgendamento__c</fullName>
    <label>Discovery Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Descricao_Empresa__c.field-meta.xml
<CustomField>
    <fullName>Descricao_Empresa__c</fullName>
    <label>Detailed Product/Service Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Desired_Business_Model__c.field-meta.xml
<CustomField>
    <fullName>Desired_Business_Model__c</fullName>
    <label>Desired Business Model</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intermediation</fullName>
            </value>
            <value>
                <fullName>Gateway</fullName>
            </value>
            <value>
                <fullName>Pix International</fullName>
            </value>
            <value>
                <fullName>Pix Roaming</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Area__c.field-meta.xml
<CustomField>
    <fullName>Lead_Area__c</fullName>
    <label>Sector (lead)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn__c</fullName>
    <label>Company LinkedIn</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LinkedInContato__c.field-meta.xml
<CustomField>
    <fullName>LinkedInContato__c</fullName>
    <label>Contact LinkedIn</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mensagem__c.field-meta.xml
<CustomField>
    <fullName>Mensagem__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NotaReclameAqui__c.field-meta.xml
<CustomField>
    <fullName>NotaReclameAqui__c</fullName>
    <label>Note &quot;Reclame Aqui&quot;</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Operacao__c.field-meta.xml
<CustomField>
    <fullName>Operacao__c</fullName>
    <label>Operação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brasil</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>Akrotiri</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Arctic Ocean</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Ashmore and Cartier Islands</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/PixMensal__c.field-meta.xml
<CustomField>
    <fullName>PixMensal__c</fullName>
    <label>Pix (% monthly share)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/previs_fat_rs__c.field-meta.xml
<CustomField>
    <fullName>previs_fat_rs__c</fullName>
    <inlineHelpText>Total processed volume expected via PagBrasil</inlineHelpText>
    <label>TPV PagBrasil</label>
    <precision>16</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_or_service_website_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_or_service_website_URL__c</fullName>
    <description>Website where the product or service will be sold. Same as KYC.</description>
    <inlineHelpText>Website where the product or service will be sold. Same as KYC.</inlineHelpText>
    <label>Product or service website URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/PSP__c.field-meta.xml
<CustomField>
    <fullName>PSP__c</fullName>
    <description>Qual é a processadora atual deste lead?</description>
    <label>PSP</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Receita_Mensal__c.field-meta.xml
<CustomField>
    <fullName>Receita_Mensal__c</fullName>
    <label>Receita Mensal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Receita_Mensal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Recurring_Payments__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Payments__c</fullName>
    <description>Já trabalha com recorrência de pagamentos?</description>
    <inlineHelpText>Antigo &quot;Recorrência&quot;</inlineHelpText>
    <label>Recurring Payments?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>Não</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Segmento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SeguidoresInstagram__c.field-meta.xml
<CustomField>
    <fullName>SeguidoresInstagram__c</fullName>
    <label>Instagram Followers</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Billing State</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/TeseProspeccao__c.field-meta.xml
<CustomField>
    <fullName>TeseProspeccao__c</fullName>
    <label>Tese de prospecção</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/TPV_Potencial__c.field-meta.xml
<CustomField>
    <fullName>TPV_Potencial__c</fullName>
    <label>TPV Potencial</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Use_Apple_Pay__c.field-meta.xml
<CustomField>
    <fullName>Use_Apple_Pay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apple Pay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Use_Google_Pay__c.field-meta.xml
<CustomField>
    <fullName>Use_Google_Pay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Google Pay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Use_One_Click_Pix__c.field-meta.xml
<CustomField>
    <fullName>Use_One_Click_Pix__c</fullName>
    <defaultValue>false</defaultValue>
    <label>1-Click Pix</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Use_Pagshield__c.field-meta.xml
<CustomField>
    <fullName>Use_Pagshield__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PagShield</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Use_Pagshield_Premium__c.field-meta.xml
<CustomField>
    <fullName>Use_Pagshield_Premium__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PagShield Premium</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Use_Pagshield_Premium_on_Demand__c.field-meta.xml
<CustomField>
    <fullName>Use_Pagshield_Premium_on_Demand__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PagShield Premium on Demand</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Use_Pagstream__c.field-meta.xml
<CustomField>
    <fullName>Use_Pagstream__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PagStream</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Use_Payout__c.field-meta.xml
<CustomField>
    <fullName>Use_Payout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/National.recordType-meta.xml
<RecordType>
    <fullName>National</fullName>
    <active>true</active>
    <businessProcess>National</businessProcess>
    <label>National</label>
</RecordType>

force-app/main/default/globalValueSets/Lead_Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Comercial</fullName>
        <label>Commercial</label>
    </customValue>
    <customValue>
        <fullName>Financeiro</fullName>
        <label>Financial</label>
    </customValue>
    <customValue>
        <fullName>Expansão</fullName>
        <label>Expansion</label>
    </customValue>
    <customValue>
        <fullName>E-commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Digital/Inovação</fullName>
        <label>Digital/Innovation</label>
    </customValue>
    <customValue>
        <fullName>Diretoria</fullName>
        <label>Board</label>
    </customValue>
    <masterLabel>Área do lead</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lead_Business_Model_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B2B</fullName>
    </customValue>
    <customValue>
        <fullName>B2C</fullName>
    </customValue>
    <customValue>
        <fullName>B2B2C</fullName>
    </customValue>
    <customValue>
        <fullName>D2C</fullName>
    </customValue>
    <masterLabel>Lead Business Model Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Receita_Mensal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Até R$50k</fullName>
    </customValue>
    <customValue>
        <fullName>R$50k até R$100k</fullName>
    </customValue>
    <customValue>
        <fullName>R$100k até R$200k</fullName>
    </customValue>
    <customValue>
        <fullName>R$200k até R$500k</fullName>
    </customValue>
    <customValue>
        <fullName>R$500k até 1M</fullName>
    </customValue>
    <customValue>
        <fullName>Acima de R$1M</fullName>
    </customValue>
    <customValue>
        <fullName>Ainda não tem operação online</fullName>
    </customValue>
    <customValue>
        <fullName>Não vende para o Brasil ainda.</fullName>
    </customValue>
    <customValue>
        <fullName>R$100k até R$500k</fullName>
    </customValue>
    <customValue>
        <fullName>Até R$100K</fullName>
    </customValue>
    <masterLabel>Receita Mensal</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {

    public static Lead createAndInsertLeadNB() {
        Lead leadNB = new Lead(
            LastName = 'Apex NB Test',
            Company = 'company nb',
            Phone = '123456789',
            MobilePhone = '234567890',
            Email = 'apexnbtest@srconsulting.io',
            LeadSource = 'Outras publicidades',
            Status = 'Pre prospection',
            RecordTypeId = getLeadRecordTypeIdByName('National'),
            AtendimentoWhatsApp__c = 'Não',
            DataAgendamento__c = Date.newInstance(2025, 8, 22),
            LinkedInContato__c = 'linkedin.com/in/apexnbtest',
            LinkedIn__c = 'companylkd',
            Mensagem__c = 'msg',
            NotaReclameAqui__c = 5,
            Receita_Mensal__c = 'Até R$50k',
            Segmento__c = 'Acessórios',
            SeguidoresInstagram__c = 1001,
            TeseProspeccao__c = 'thesis',
            Descricao_Empresa__c = 'detailed description',
            Product_or_service_website_URL__c = 'apexnbteste.com.br',
            Ag_ncia__c = 'agency nb',
            Operacao__c = 'Inbound',
            Data_de_indicacao__c = Date.newInstance(2025, 8, 22),
            cf_email_indicador__c = 'apexnbtest@srconsulting.io',
            previs_fat_rs__c = 100,
            PSP__c = 'psp',
            Pais__c = 'Brazil',
            Boleto_Share__c = 1,
            Cartao_Credito_Mensal__c = 1,
            PixMensal__c = 1,
            Lead_Area__c = 'Diretoria',
            AverageSalesTicket__c = 100,
            Business_Model_Type__c = 'B2B',
            CNPJ__c = '72784626000147',
            Cartao_Debito_Mensal__c = 1,
            City__c = 'Congonhas',
            Desired_Business_Model__c = 'Intermediation',
            Product_Type__c = 'Physical',
            Recurring_Payments__c = 'Sim',
            State__c = 'SP',
            TPV_Potencial__c = 100,
            Use_Apple_Pay__c = true,
            Use_Google_Pay__c = true,
            Use_One_Click_Pix__c = true,
            Use_Pagshield_Premium__c = false,
            Use_Pagshield_Premium_on_Demand__c = false,
            Use_Pagshield__c = false,
            Use_Pagstream__c = true,
            Use_Payout__c = true,
            Contact_City__c = 'contactcity',
            Integration_Type__c = 'JS',
            Payment_Methods__c = 'Pix',
            Product_Category__c = '5122'
        );
        insert leadNB;
        return leadNB;
    }

    public static Lead createAndInsertLeadXB() {
        Lead leadXB = new Lead(
            LastName = 'Apex XB Test',
            Company = 'company xb',
            Phone = '234567890',
            MobilePhone = '098765432',
            Email = 'apexxbtest@srconsulting.io',
            LeadSource = 'Social | LinkedIn',
            Status = 'Pre prospection',
            RecordTypeId = getLeadRecordTypeIdByName('Cross-border'),
            AtendimentoWhatsApp__c = 'Não',
            DataAgendamento__c = Date.newInstance(2025, 8, 22),
            LinkedInContato__c = 'linkedin.com/in/apexnbtest',
            LinkedIn__c = 'companylkdxb',
            Mensagem__c = 'msg xb',
            NotaReclameAqui__c = 4,
            Receita_Mensal__c = 'Acima de R$1M',
            Segmento__c = 'Cosméticos',
            SeguidoresInstagram__c = 1000001,
            TeseProspeccao__c = 'thesis xb',
            Descricao_Empresa__c = 'detailed xb description',
            Product_or_service_website_URL__c = 'apexxbteste.com.br',
            Ag_ncia__c = 'agency xb',
            Operacao__c = 'Outbound',
            Data_de_indicacao__c = Date.newInstance(2025, 8, 22),
            cf_email_indicador__c = 'apexxbtest@srconsulting.io',
            previs_fat_rs__c = 200,
            PSP__c = 'psp',
            Pais__c = 'United States of America',
            Boleto_Share__c = 2,
            Cartao_Credito_Mensal__c = 2,
            PixMensal__c = 2,
            Lead_Area__c = 'Comercial',
            AverageSalesTicket__c = 200,
            Business_Model_Type__c = 'B2B2C',
            City__c = 'New York',
            Desired_Business_Model__c = 'Intermediation',
            Product_Type__c = 'Digital',
            Recurring_Payments__c = 'Não',
            State__c = 'New York',
            TPV_Potencial__c = 200,
            Use_Apple_Pay__c = false,
            Use_Google_Pay__c = false,
            Use_One_Click_Pix__c = false,
            Use_Pagshield_Premium__c = false,
            Use_Pagshield_Premium_on_Demand__c = false,
            Use_Pagshield__c = false,
            Use_Pagstream__c = false,
            Use_Payout__c = false,
            VAT__c = '793198392345673',
            Integration_Type__c = 'Vtex',
            Payment_Methods__c = 'Cartão de Crédito',
            Product_Category__c = '5122'
        );
        insert leadXB;
        return leadXB;
    }

    public static Id getLeadRecordTypeIdByName(String recordTypeName) {
        Map<String, Schema.RecordTypeInfo> recordTypeMap = Schema.SObjectType.Lead.getRecordTypeInfosByName();

        if (recordTypeMap.containsKey(recordTypeName)) {
            return recordTypeMap.get(recordTypeName).getRecordTypeId();
        } else {
            throw new RecordTypeNotFoundException('RecordType "' + recordTypeName + '" não encontrado para Lead.');
        }
    }

    public class RecordTypeNotFoundException extends Exception {}
}