force-app/main/default/objects/Opportunity/fields/ApplePay__c.field-meta.xml
<CustomField>
    <fullName>ApplePay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apple Pay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AverageSalesTicket__c.field-meta.xml
<CustomField>
    <fullName>AverageSalesTicket__c</fullName>
    <inlineHelpText>Average Order Value</inlineHelpText>
    <label>Average Order Value</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessModel__c.field-meta.xml
<CustomField>
    <fullName>BusinessModel__c</fullName>
    <label>Desired Business Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessModel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessModelType__c.field-meta.xml
<CustomField>
    <fullName>BusinessModelType__c</fullName>
    <label>Business Model Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessModelType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GooglePay__c.field-meta.xml
<CustomField>
    <fullName>GooglePay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Google Pay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Integracao__c.field-meta.xml
<CustomField>
    <fullName>Integracao__c</fullName>
    <label>Plataforma Utilizada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InHouse</fullName>
            </value>
            <value>
                <fullName>Shopify</fullName>
            </value>
            <value>
                <fullName>Shopify - Buda</fullName>
            </value>
            <value>
                <fullName>Shopify - CartX</fullName>
            </value>
            <value>
                <fullName>Woocommerce</fullName>
            </value>
            <value>
                <fullName>Magento</fullName>
            </value>
            <value>
                <fullName>Vtex</fullName>
            </value>
            <value>
                <fullName>PrestaShop</fullName>
            </value>
            <value>
                <fullName>OpenCart</fullName>
            </value>
            <value>
                <fullName>ACI</fullName>
            </value>
            <value>
                <fullName>Computop</fullName>
            </value>
            <value>
                <fullName>Salesforce CC</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>NuvemShop</fullName>
            </value>
            <value>
                <fullName>Loja Integrada</fullName>
            </value>
            <value>
                <fullName>Tray</fullName>
            </value>
            <value>
                <fullName>Get Commerce</fullName>
            </value>
            <value>
                <fullName>Outra</fullName>
            </value>
            <value>
                <fullName>InHouse / API</fullName>
            </value>
            <value>
                <fullName>PagBrasil.js</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>Payment Link + API</fullName>
            </value>
            <value>
                <fullName>Paymentl LInk Offline</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>JS</fullName>
                <isActive>false</isActive>
                <label>JS</label>
            </value>
            <value>
                <fullName>Link de Pagamentos</fullName>
                <isActive>false</isActive>
                <label>Link de Pagamentos</label>
            </value>
            <value>
                <fullName>OutraSpecify</fullName>
                <isActive>false</isActive>
                <label>OutraSpecify</label>
            </value>
            <value>
                <fullName>PB Checkout</fullName>
                <isActive>false</isActive>
                <label>PB Checkout</label>
            </value>
            <value>
                <fullName>Shopify with Buda</fullName>
                <isActive>false</isActive>
                <label>Shopify with Buda</label>
            </value>
            <value>
                <fullName>Shopify with Cart Panda</fullName>
                <isActive>false</isActive>
                <label>Shopify with Cart Panda</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IntegrationType__c.field-meta.xml
<CustomField>
    <fullName>IntegrationType__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IntegrationType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NationalPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>NationalPaymentMethod__c</fullName>
    <label>Payment Methods</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NationalPaymentMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/nb_receita_mensal__c.field-meta.xml
<CustomField>
    <fullName>nb_receita_mensal__c</fullName>
    <description>Faixa de faturamento mensal das oportunidades nacionais, em R$.</description>
    <inlineHelpText>Merchant’s potential of total processed volume</inlineHelpText>
    <label>Potential TPV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentRecurrence__c.field-meta.xml
<CustomField>
    <fullName>PaymentRecurrence__c</fullName>
    <inlineHelpText>Already works with recurring payments?</inlineHelpText>
    <label>Recurring Payments?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>Não</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payout__c.field-meta.xml
<CustomField>
    <fullName>Payout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/previs_fat_rs__c.field-meta.xml
<CustomField>
    <fullName>previs_fat_rs__c</fullName>
    <description>Qual é a previsão de faturamento mensal (R$) do lead no momento de qualificação?</description>
    <inlineHelpText>Total processed volume expected via PagBrasil</inlineHelpText>
    <label>PagBrasil TPV</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProductClass__c.field-meta.xml
<CustomField>
    <fullName>ProductClass__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductClass</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TierCS__c.field-meta.xml
<CustomField>
    <fullName>TierCS__c</fullName>
    <label>Tier CS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Top Tier</fullName>
            </value>
            <value>
                <fullName>High Tier</fullName>
            </value>
            <value>
                <fullName>Middle Touch</fullName>
            </value>
            <value>
                <fullName>Low Touch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Transacoes_Mensais__c.field-meta.xml
<CustomField>
    <fullName>Transacoes_Mensais__c</fullName>
    <label>Number of Monthly Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UsePagstream__c.field-meta.xml
<CustomField>
    <fullName>UsePagstream__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Will Pagstream be used as the recurring payment solution?</description>
    <inlineHelpText>Will Pagstream be used as the recurring payment solution?</inlineHelpText>
    <label>PagStream</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/CustomerAcceptance__c.field-meta.xml
<CustomField>
    <fullName>CustomerAcceptance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Acceptance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/OtherQuoteAccepted__c.field-meta.xml
<CustomField>
    <fullName>OtherQuoteAccepted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Other quote was accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/BusinessModel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Intermediation</fullName>
    </customValue>
    <customValue>
        <fullName>Gateway</fullName>
    </customValue>
    <customValue>
        <fullName>Pix International</fullName>
    </customValue>
    <customValue>
        <fullName>Pix Roaming</fullName>
    </customValue>
    <masterLabel>Business Model</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/BusinessModelType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B2B</fullName>
    </customValue>
    <customValue>
        <fullName>B2C</fullName>
    </customValue>
    <customValue>
        <fullName>B2B2C</fullName>
    </customValue>
    <customValue>
        <fullName>D2C</fullName>
    </customValue>
    <masterLabel>Business Model Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NationalPaymentMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pix</fullName>
    </customValue>
    <customValue>
        <fullName>Cartão de Crédito</fullName>
    </customValue>
    <customValue>
        <fullName>Débito Flash</fullName>
    </customValue>
    <customValue>
        <fullName>Boleto Flash</fullName>
    </customValue>
    <masterLabel>Métodos de Pagamentos - Nacional</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProductClass.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5122</fullName>
        <label>Drugstores</label>
    </customValue>
    <customValue>
        <fullName>5300</fullName>
        <label>Wholesale Clubs</label>
    </customValue>
    <customValue>
        <fullName>5331</fullName>
        <label>Variety Stores</label>
    </customValue>
    <customValue>
        <fullName>5499</fullName>
        <label>Grocery Stores and Supermarkets</label>
    </customValue>
    <customValue>
        <fullName>5651</fullName>
        <label>Clothing</label>
    </customValue>
    <customValue>
        <fullName>5732</fullName>
        <label>Electronics Stores</label>
    </customValue>
    <customValue>
        <fullName>5734</fullName>
        <label>Computer Software</label>
    </customValue>
    <customValue>
        <fullName>5921</fullName>
        <label>Beer, Wine, Liquor Stores</label>
    </customValue>
    <customValue>
        <fullName>5977</fullName>
        <label>Cosmetic Stores</label>
    </customValue>
    <customValue>
        <fullName>8299</fullName>
        <label>Schools and Educational Services</label>
    </customValue>
    <customValue>
        <fullName>8999</fullName>
        <label>Professional Services</label>
    </customValue>
    <customValue>
        <fullName>7299</fullName>
        <label>Other</label>
    </customValue>
    <masterLabel>Product Class</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTriggerHelper.cls
/**
 * @description       : 
 * @author            : aydhan.passos
 * @group             : 
 * @last modified on  : 04-10-2025
 * @last modified by  : aydhan.passos
**/
public with sharing class OpportunityTriggerHelper {
   
    /**
    * @description adicionado regra de opp sincronizada para não gerar erro qdo criar nova cotação
    * @author Hersilio Belini de Oliveira | 2025-02-18
    **/
    public static void verifyRemovedSyncedQuoteId( List<Opportunity> newOppList, Map<Id, Opportunity> oldOppMap){

        for(Opportunity opp : newOppList){
            if(opp.SyncedQuoteId == null && oldOppMap.get(opp.Id).SyncedQuoteId != null){
                opp.Pricebook2Id = null;
            }
        }
    }

    /**
    * @description popula a data de fechamento com 90 dias automaticamente.
    * @author aydhan.passos | 04-04-2025 
    * @param newOppList 
    **/
    public static void autoFillOppFields( List<Opportunity> newOppList){

        for(Opportunity opp : newOppList){
            opp.CloseDate = Date.today().addDays(90);
            opp.StageName = 'Discovery';
        }
    }

    /**
    * @description validate change fields
    * @author Hersilio Belini de Oliveira | 2024-12-24
    **/
    public static void validateChangeFields(List<Opportunity> newOppList, Map<Id, Opportunity> oldOppMap){
        Map<Id, List<Quote>> quoteMap = OpportunityTriggerHelper.getQuotesByOpportunityIds(oldOppMap.keyset());
        List<Quote> quotesToCancel = new List<Quote>();
        Map<String, Quote> quotesToSync = new Map<String, Quote>();

        for(Opportunity opp : newOppList){

            if(OpportunityTriggerHelper.hasFieldModified(opp, oldOppMap)){

                if(opp.StageName != 'Hibernate' && opp.StageName != 'Discovery' && opp.StageName != 'Negotiation'){
                    opp.addError('Status da oportunidade não permite alteração de campos');
                    break;
                }

                List<Quote> quotes = quoteMap.get(opp.Id);

                if(quotes != null && quotes.size() > 0 && OpportunityTriggerHelper.canCancelQuotes(opp, quotes)){
                    for(Quote quote : quotes){
                        if(quote.Status == 'Draft' || quote.Status == 'Approved' || quote.Status == 'Rejected'){
                            quote.Status = 'Canceled';
                            quotesToCancel.add(quote);
                            continue;
                        }
                    }
                }
            }
        }

        if(!quotesToCancel.isEmpty()){
            TriggerHandler.bypass('QuoteTriggerHandler');
            update quotesToCancel;
            TriggerHandler.clearBypass('QuoteTriggerHandler');
        }
    }


    /**
    * @description can cancel quotes
    * @author Hersilio Belini de Oliveira | 2024-12-24
    * @param opp
    * @param quotes
    * @return Boolean
    **/
    private static Boolean canCancelQuotes(Opportunity opp, List<Quote> quotes){
        for(Quote quote : quotes){

            if(quote.Status != null && quote.Status.toLowerCase().contains('pending approval')){
                opp.addError('Alteração de campos não permitida, existe cotação em aprovação');
                return false;
            }

            if(quote.IsSyncing){
                opp.addError('Alteração de campos não permitida, existe cotação sincronizada com a oportunidade.');
                return false;
            }
        }

        return true;
    }

    /**
    * @description has field modified
    * @author Hersilio Belini de Oliveira | 2024-12-24
    * @param opp
    * @return Boolean
    **/
    private static Boolean hasFieldModified(Opportunity opp, Map<Id, Opportunity> oldOppMap){
        Opportunity oldOpp = oldOppMap.get(opp.Id);

        return opp.BusinessModel__c != oldOpp.BusinessModel__c ||
        opp.Integracao__c != oldOpp.Integracao__c ||
        opp.IntegrationType__c != oldOpp.IntegrationType__c ||
        opp.NationalPaymentMethod__c != oldOpp.NationalPaymentMethod__c ||
        opp.PaymentRecurrence__c != oldOpp.PaymentRecurrence__c ||
        opp.UsePagstream__c != oldOpp.UsePagstream__c ||
        opp.Payout__c != oldOpp.Payout__c ||
        opp.GooglePay__c != oldOpp.GooglePay__c ||
        opp.ApplePay__c != oldOpp.ApplePay__c ||
        opp.TierCS__c != oldOpp.TierCS__c ||
        opp.ProductClass__c != oldOpp.ProductClass__c ||
        opp.AverageSalesTicket__c != oldOpp.AverageSalesTicket__c ||
        opp.Transacoes_Mensais__c != oldOpp.Transacoes_Mensais__c ||
        opp.previs_fat_rs__c != oldOpp.previs_fat_rs__c ||
        opp.nb_receita_mensal__c != oldOpp.nb_receita_mensal__c ||
        opp.BusinessModelType__c != oldOpp.BusinessModelType__c;
    }

    /**
    * @description get quote
    * @author Hersilio Belini de Oliveira | 2024-12-20
    * @param oppIds
    * @return List<Quote>
    **/
    private static Map<Id, List<Quote>> getQuotesByOpportunityIds(Set<Id> oppIds){
        List<Quote> quotes = [SELECT Id, Name, OpportunityId, Status, IsSyncing FROM Quote WHERE OpportunityId IN :oppIds AND Status != 'Canceled'];

        Map<Id, List<Quote>> quotesMap = new Map<Id, List<Quote>>();

        for(Quote quote : quotes){
            if(!quotesMap.containsKey(quote.OpportunityId)){
                quotesMap.put(quote.OpportunityId, new List<Quote>());
            }

            quotesMap.get(quote.OpportunityId).add(quote);
        }

        return quotesMap;
    }

    /**
     * @description update related opportunity quotes when the synced quote is removed
     * @author luis.tavares | 2025-04-22
     * @param newOppList, oldOppMap
     * @return void
     **/
     public static void updateQuotesOnSyncedQuoteRemoval(List<Opportunity> newOppList, Map<Id, Opportunity> oldOppMap) {
         List<Quote> quotesToUpdate = new List<Quote>();
         Map<Id, List<Quote>> quotesMap = OpportunityTriggerHelper.getQuotesByOpportunityIds(new Set<Id>((new Map<Id, Opportunity>(newOppList)).keySet()));

         for (Opportunity newOpp : newOppList) {
            Opportunity oldOpp = oldOppMap.get(newOpp.Id);


            if (oldOpp.SyncedQuoteId != null && newOpp.SyncedQuoteId == null) {
                // se a SyncedQuoteId foi removida significa que a quote antes sincronizada agora foi dessincronizada
                // então, precisamos atualizar as flags de CustomerAcceptance__c e OtherQuoteAccepted__c para false em todas quotes relacionadas a oportunidade
                List<Quote> opportunityQuotes = quotesMap.get(newOpp.Id);


                if (opportunityQuotes != null && !opportunityQuotes.isEmpty()) {
                    for (Quote quote : opportunityQuotes) {
                        quote.CustomerAcceptance__c = false;
                        quote.OtherQuoteAccepted__c = false;

                        quotesToUpdate.add(quote);
                    }
                }
            }
        }

        if (!quotesToUpdate.isEmpty()) {
            TriggerHandler.bypass('QuoteTriggerHandler');
            update quotesToUpdate;
            TriggerHandler.clearBypass('QuoteTriggerHandler');
        }
    }
}