force-app/main/default/objects/Opportunity/fields/OpportunityKYCLegalApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>OpportunityKYCLegalApprovalStatus__c</fullName>
    <label>Opportunity KYC Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityRCCLegalApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>OpportunityRCCLegalApprovalStatus__c</fullName>
    <label>Opportunity RCC Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RCC__c/RCC__c.object-meta.xml
<CustomObject>
    <label>RCC</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>RCC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RCCS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RCC__c/fields/LegalApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalApprovalStatus__c</fullName>
    <label>Legal Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RCC__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RCCS</relationshipLabel>
    <relationshipName>RCCS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/LegalApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Added</fullName>
        <default>true</default>
        <label>Added</label>
    </customValue>
    <customValue>
        <fullName>Approval Requested</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Approval Legal</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Legal Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RCCTriggerHelper.cls
public with sharing class RCCTriggerHelper {
    public static void updateOpportunityLegalApprovalStatus(List<RCC__c> newRCCList, Map<Id, RCC__c> oldRCCMap) {
        Set<Id> oppIds = new Set<Id>();
        for (RCC__c rcc : newRCCList) {
            if (rcc.Opportunity__c != null) {
                oppIds.add(rcc.Opportunity__c);
            }
        }

        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>([SELECT Id, RecordTypeId, OpportunityRCCLegalApprovalStatus__c, OpportunityKYCLegalApprovalStatus__c FROM Opportunity WHERE Id IN :oppIds]);

        for (RCC__c rcc : newRCCList) {
            if (rcc.Opportunity__c != null && oppMap.containsKey(rcc.Opportunity__c)) {
                Opportunity opp = oppMap.get(rcc.Opportunity__c);
                if (rcc.LegalApprovalStatus__c != oldRCCMap.get(rcc.Id).LegalApprovalStatus__c) {
                    opp.OpportunityRCCLegalApprovalStatus__c = rcc.LegalApprovalStatus__c;
                }
            }
        }

        if (!oppMap.isEmpty()) {
            update oppMap.values();
        }
        
        // OpportunityTriggerHelper.submitKYCAndRCCForApprovalHandler(oppMap.values());
    }
}